import type { Database, Tables, TablesInsert, TablesUpdate } from "@/integrations/supabase/types";

export type Invoice = Tables<"invoices">;
export type InvoiceInsert = TablesInsert<"invoices">;
export type InvoiceUpdate = TablesUpdate<"invoices">;
export type InvoiceLine = Tables<"invoice_lines">;
export type InvoiceLineInsert = TablesInsert<"invoice_lines">;
export type InvoiceLineUpdate = TablesUpdate<"invoice_lines">;
export type PaymentReceived = Tables<"payments_received">;
export type PaymentReceivedInsert = TablesInsert<"payments_received">;
export type PaymentMade = Tables<"payments_made">;
export type PaymentMadeInsert = TablesInsert<"payments_made">;
export type StockMovement = Tables<"stock_movements">;
export type StockMovementInsert = TablesInsert<"stock_movements">;
export type JournalEntry = Tables<"journal_entries">;
export type JournalLine = Tables<"journal_lines">;
export type Package = Tables<"packages">;
export type PackageInsert = TablesInsert<"packages">;
export type PackageLine = Tables<"package_lines">;
export type PackageLineInsert = TablesInsert<"package_lines">;
export type Shipment = Tables<"shipments">;
export type ShipmentInsert = TablesInsert<"shipments">;
export type SalesOrder = Tables<"sales_orders">;
export type SalesOrderLine = Tables<"sales_order_lines">;
export type Customer = Tables<"customers">;
export type Item = Tables<"items">;
export type Warehouse = Tables<"warehouses">;
export type ChartOfAccount = Tables<"chart_of_accounts">;
export type AppRole = Database["public"]["Enums"]["app_role"];
export type Payment = PaymentReceived | PaymentMade;
export type Tenant = Tables<"tenants"> & {
  legal_name?: string | null;
  trading_name?: string | null;
  registration_number?: string | null;
  tax_id?: string | null;
  vat_number?: string | null;
  business_type?: string | null;
  industry?: string | null;
  description?: string | null;
  year_established?: number | null;
  email?: string | null;
  phone?: string | null;
  website?: string | null;
  address_line1?: string | null;
  address_line2?: string | null;
  city?: string | null;
  state_province?: string | null;
  postal_code?: string | null;
  country?: string | null;
  timezone?: string | null;
  date_format?: string | null;
  number_format?: string | null;
  fiscal_year_start?: string | null;
  fiscal_year_end?: string | null;
  tax_authority?: string | null;
  tax_regime?: string | null;
  tax_inclusive_pricing?: boolean | null;
  logo_url?: string | null;
  signature_url?: string | null;
  stamp_url?: string | null;
};

