import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Download, Printer } from "lucide-react";
import { db } from "@/lib/typed-db";
import { useAuth } from "@/hooks/use-auth";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { PurchaseReportFilters, type ReportFilterState } from "@/components/purchase-report-filters";

export function DatabaseReportPage({ domain, report, title, supplierId }: { domain: "purchases" | "expenses" | "manufacturing"; report: string; title: string; supplierId?: string }) {
  const { tenant } = useAuth(); const today = new Date().toISOString().slice(0, 10); const [filters, setFilters] = useState<ReportFilterState>({ dateFrom: `${new Date().getFullYear()}-01-01`, dateTo: today, asOf: today, supplierId: supplierId ?? "all", employeeId: "all", department: "all", currency: "all", status: "all" });
  const { data, isLoading } = useQuery({ queryKey: ["database-report", domain, report, filters], enabled: Boolean(tenant?.id), queryFn: async () => { const result = domain === "manufacturing" ? await (db as any).rpc("get_manufacturing_performance_report", { _report: report, _date_from: filters.dateFrom || null, _date_to: filters.dateTo || null }) : domain === "purchases" ? await db.rpc("get_procurement_report", { _report: report, _date_from: filters.dateFrom || null, _date_to: filters.dateTo || null, _supplier_id: filters.supplierId === "all" ? null : filters.supplierId, _currency: filters.currency === "all" ? null : filters.currency, _status: filters.status === "all" ? null : filters.status, _as_of: filters.asOf || null }) : await db.rpc("get_expense_report", { _report: report, _date_from: filters.dateFrom || null, _date_to: filters.dateTo || null, _employee_id: filters.employeeId === "all" ? null : filters.employeeId, _department: filters.department === "all" ? null : filters.department, _currency: filters.currency === "all" ? null : filters.currency, _status: filters.status === "all" ? null : filters.status }); if (result.error) throw result.error; return result.data as { summary?: Record<string, any>; rows?: Record<string, any>[] }; } });
  const rows = data?.rows ?? []; const columns = useMemo(() => Array.from(new Set(rows.flatMap((row) => Object.keys(row)))).slice(0, 12), [rows]);
  const exportCsv = () => { const csv = [columns.join(","), ...rows.map((row) => columns.map((column) => JSON.stringify(row[column] ?? "")).join(","))].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = `${domain}-${report}.csv`; link.click(); URL.revokeObjectURL(link.href); };
  return <div className="min-h-full bg-muted/20 p-6"><div className="mx-auto max-w-[1500px] space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold">{title}</h1><p className="text-sm text-muted-foreground">Database-driven {domain} report using the selected date semantics and filters.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => window.print()}><Printer className="mr-2 h-4 w-4" />Print</Button><Button variant="outline" onClick={exportCsv} disabled={!rows.length}><Download className="mr-2 h-4 w-4" />CSV</Button></div></div><PurchaseReportFilters value={filters} onChange={setFilters} /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(data?.summary ?? {}).slice(0, 8).map(([key, value]) => <Card className="p-4" key={key}><div className="text-xs uppercase text-muted-foreground">{key.replaceAll("_", " ")}</div><div className="mt-1 font-mono text-xl font-semibold">{typeof value === "number" ? value.toLocaleString(undefined, { maximumFractionDigits: 2 }) : String(value ?? "—")}</div></Card>)}</div><Card className="overflow-auto p-0"><table className="w-full text-sm"><thead className="bg-muted/50 text-left text-xs text-muted-foreground"><tr>{columns.map((column) => <th className="whitespace-nowrap p-3" key={column}>{column.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{isLoading ? <tr><td className="p-8 text-center" colSpan={columns.length || 1}>Loading report...</td></tr> : rows.length ? rows.map((row, index) => <tr className="border-t" key={row.id ?? index}>{columns.map((column) => <td className="whitespace-nowrap p-3" key={column}>{String(row[column] ?? "—")}</td>)}</tr>) : <tr><td className="p-8 text-center text-muted-foreground" colSpan={columns.length || 1}>No data for the selected filters.</td></tr>}</tbody></table></Card></div></div>;
}