import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { db } from "@/lib/typed-db";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export function ExpensesListPage() {
  const [status, setStatus] = useState("all"); const [search, setSearch] = useState("");
  const { data: expenses = [], isLoading } = useQuery({ queryKey: ["expenses", "phase6-list", status, search], queryFn: async () => { let query = db.from("expenses").select("id,number,date,employee_id,category,merchant,amount,total,currency,status,reimbursement_status,receipt_status").is("deleted_at", null).order("date", { ascending: false }); if (status !== "all") query = query.eq("status", status); if (search.trim()) query = query.or(`number.ilike.%${search.trim()}%,merchant.ilike.%${search.trim()}%,category.ilike.%${search.trim()}%`); const { data, error } = await query; if (error) throw error; return (data ?? []) as Record<string, any>[]; } });
  return <div className="h-full overflow-auto bg-background p-6"><div className="mx-auto max-w-7xl space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-xl font-semibold">Expenses</h1><p className="text-sm text-muted-foreground">Employee expenses, receipt policy, approvals, posting, and reimbursement.</p></div><Link to="/expenses/$id" params={{ id: "new" }}><Button>New Expense</Button></Link></div><div className="flex gap-2"><Input className="w-64" placeholder="Search expense, merchant, category" value={search} onChange={(event) => setSearch(event.target.value)} /><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-48"><SelectValue placeholder="Status" /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{["Draft", "Submitted", "Pending Approval", "Approved", "Rejected", "Posted", "Cancelled"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><Card className="overflow-hidden"><table className="w-full text-sm"><thead className="bg-muted/50 text-left text-xs text-muted-foreground"><tr><th className="p-3">Expense #</th><th className="p-3">Date</th><th className="p-3">Merchant</th><th className="p-3">Category</th><th className="p-3 text-right">Total</th><th className="p-3">Receipt</th><th className="p-3">Accounting</th><th className="p-3">Reimbursement</th></tr></thead><tbody>{isLoading ? <tr><td className="p-8 text-center" colSpan={8}>Loading...</td></tr> : expenses.map((expense) => <tr className="border-t" key={expense.id}><td className="p-3"><Link className="text-primary hover:underline" to="/expenses/$id" params={{ id: expense.id }}>{expense.number ?? expense.id.slice(0, 8)}</Link></td><td className="p-3">{expense.date}</td><td className="p-3">{expense.merchant ?? "—"}</td><td className="p-3">{expense.category}</td><td className="p-3 text-right font-mono">{expense.currency} {Number(expense.total ?? expense.amount ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td><td className="p-3">{expense.receipt_status}</td><td className="p-3">{expense.status}</td><td className="p-3">{expense.reimbursement_status}</td></tr>)}</tbody></table></Card></div></div>;
}