import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { db } from "@/lib/typed-db";
import { toast } from "sonner";
import { Loader2, PackageCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ReceiptLineTable } from "@/components/receipt-line-table";
import { ServiceConfirmationForm } from "@/components/service-confirmation-form";

export function PurchaseReceiptDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const [orderId, setOrderId] = useState("");
  const [warehouseId, setWarehouseId] = useState("");
  const [receiptType, setReceiptType] = useState("Goods");
  const [values, setValues] = useState<Record<string, { accepted: string; rejected: string }>>({});
  const [service, setService] = useState({ servicePeriodStart: "", servicePeriodEnd: "", acceptedBy: "", description: "" });
  const { data: orders = [] } = useQuery({ queryKey: ["purchase_orders", "receivable"], enabled: open, queryFn: async () => { const { data, error } = await db.from("purchase_orders").select("id,number,supplier_id,currency,status").is("deleted_at", null).in("status", ["Approved", "Sent", "Acknowledged"]); if (error) throw error; return (data ?? []) as Record<string, any>[]; } });
  const { data: warehouses = [] } = useQuery({ queryKey: ["warehouses", "receipts"], enabled: open, queryFn: async () => { const { data, error } = await db.from("warehouses").select("id,name").is("deleted_at", null).order("name"); if (error) throw error; return (data ?? []) as Record<string, any>[]; } });
  const { data: lines = [], isLoading } = useQuery({ queryKey: ["purchase_orders", orderId, "receipt-lines"], enabled: Boolean(orderId), queryFn: async () => { const [{ data: lineRows, error: lineError }, { data: statusRows, error: statusError }] = await Promise.all([db.from("purchase_order_lines").select("id,item_id,description,quantity,unit_price").eq("document_id", orderId).is("deleted_at", null).order("line_no"), db.rpc("get_purchase_order_receiving_status", { _order_id: orderId })]); if (lineError) throw lineError; if (statusError) throw statusError; const statusMap = Object.fromEntries((statusRows ?? []).map((row: Record<string, any>) => [row.line_id, row])); return (lineRows ?? []).map((line: Record<string, any>) => ({ ...line, ...statusMap[line.id], item_name: line.description ?? line.item_id })); } });
  const selected = useMemo(() => lines.map((line) => ({ purchase_order_line_id: line.id, accepted_quantity: Number(values[line.id]?.accepted ?? 0), rejected_quantity: Number(values[line.id]?.rejected ?? 0), unit_price: line.unit_price, description: service.description || line.description })).filter((line) => line.accepted_quantity > 0 || line.rejected_quantity > 0), [lines, values, service.description]);
  const submit = async () => { if (!orderId) return toast.error("Select a purchase order"); if (!selected.length) return toast.error("Enter at least one quantity"); const { error } = await db.rpc("create_purchase_receipt", { _purchase_order_id: orderId, _warehouse_id: receiptType === "Goods" ? warehouseId || null : null, _receipt_type: receiptType, _lines: selected, _description: service.description || null, _service_period_start: service.servicePeriodStart || null, _service_period_end: service.servicePeriodEnd || null }); if (error) return toast.error(error.message); toast.success("Receipt created as Draft"); setValues({}); setOrderId(""); onOpenChange(false); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-5xl"><DialogHeader><DialogTitle className="flex items-center gap-2"><PackageCheck className="h-4 w-4" />New Purchase Receipt</DialogTitle></DialogHeader><div className="grid gap-4"><div className="grid gap-3 sm:grid-cols-3"><div className="grid gap-1.5"><Label>Purchase Order</Label><Select value={orderId} onValueChange={(value) => { setOrderId(value); setValues({}); }}><SelectTrigger><SelectValue placeholder="Select PO" /></SelectTrigger><SelectContent>{orders.map((order) => <SelectItem key={order.id} value={order.id}>{order.number ?? order.id}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-1.5"><Label>Receipt Type</Label><Select value={receiptType} onValueChange={setReceiptType}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Goods">Goods Receipt</SelectItem><SelectItem value="Service">Service Confirmation</SelectItem></SelectContent></Select></div><div className="grid gap-1.5"><Label>Warehouse</Label><Select value={warehouseId} onValueChange={setWarehouseId} disabled={receiptType === "Service"}><SelectTrigger><SelectValue placeholder={receiptType === "Service" ? "Not required" : "Select warehouse"} /></SelectTrigger><SelectContent>{warehouses.map((warehouse) => <SelectItem key={warehouse.id} value={warehouse.id}>{warehouse.name}</SelectItem>)}</SelectContent></Select></div></div>{receiptType === "Service" && <ServiceConfirmationForm values={service} onChange={(key, value) => setService((current) => ({ ...current, [key]: value }))} />}{orderId && (isLoading ? <Loader2 className="mx-auto h-5 w-5 animate-spin" /> : <ReceiptLineTable lines={lines} values={values} onChange={(lineId, field, value) => setValues((current) => ({ ...current, [lineId]: { accepted: current[lineId]?.accepted ?? "", rejected: current[lineId]?.rejected ?? "", [field]: value } }))} />)}</div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={submit}>Create Draft Receipt</Button></DialogFooter></DialogContent></Dialog>;
}