import {
  BarChart3,
  Boxes,
  Factory,
  FileBarChart,
  Package,
  ShoppingCart,
  Store,
  Users,
  WalletCards,
} from "lucide-react";
import type { ReportsListingConfig } from "@/components/reports-listing-page";

const row = (
  id: string,
  title: string,
  description: string,
  url: string,
  category: string,
  icon = FileBarChart,
  iconClass = "bg-blue-500/10 text-blue-700",
) => ({ id, title, description, url, category, icon, iconClass });

export const salesReportsConfig: ReportsListingConfig = {
  module: "sales",
  title: "Sales Reports",
  description: "View, analyze and export your sales performance and transaction reports.",
  categories: ["All", "Sales", "Customers", "Receivables", "Products"],
  kpis: [
    { label: "Revenue YTD", value: null, tone: "bg-blue-500/10 text-blue-700", icon: WalletCards },
    {
      label: "Orders YTD",
      value: null,
      suffix: "orders",
      tone: "bg-cyan-500/10 text-cyan-700",
      icon: ShoppingCart,
    },
    {
      label: "Gross Profit",
      value: null,
      tone: "bg-emerald-500/10 text-emerald-700",
      icon: BarChart3,
    },
    {
      label: "Outstanding Receivables",
      value: null,
      tone: "bg-orange-500/10 text-orange-700",
      icon: WalletCards,
    },
  ],
  reports: [
    row(
      "sales-summary",
      "Sales Summary",
      "Review posted sales performance and current period revenue.",
      "/reports/sales",
      "Sales",
      BarChart3,
    ),
    row(
      "sales-customers",
      "Sales by Customer",
      "Compare customer activity, revenue, and order contribution.",
      "/reports/sales/customers",
      "Customers",
      Users,
    ),
    row(
      "sales-products",
      "Sales by Product",
      "Review item-level sales activity and performance.",
      "/reports/sales/products",
      "Products",
      Package,
    ),
    row(
      "customer-receivables",
      "Customer Receivables",
      "Review outstanding customer balances and payment status.",
      "/reports/sales/receivables",
      "Receivables",
      WalletCards,
    ),
    row(
      "collections",
      "Collections",
      "Track payments, overdue invoices, DSO, and unallocated receipts.",
      "/reports/sales/collections",
      "Receivables",
      WalletCards,
    ),
    row(
      "customer-statements",
      "Customer Statements",
      "Review invoice, payment, credit-note, and running-balance history.",
      "/reports/sales/customer-statements",
      "Customers",
      FileBarChart,
    ),
    row(
      "salespeople",
      "Sales by Salesperson",
      "Rank sales performance and quote conversion.",
      "/reports/sales/salespeople",
      "Sales",
      Users,
    ),
    row(
      "quote-conversion",
      "Quote Conversion",
      "Follow the quote-to-order funnel.",
      "/reports/sales/quote-conversion",
      "Sales",
      BarChart3,
    ),
    row(
      "fulfillment",
      "Order Fulfillment",
      "Compare order fulfillment, invoicing, and payment progress.",
      "/reports/sales/fulfillment",
      "Sales",
      ShoppingCart,
    ),
    row(
      "profitability",
      "Sales Profitability",
      "Analyze revenue, COGS, gross profit, and margin.",
      "/reports/sales/profitability",
      "Sales",
      BarChart3,
    ),
    row(
      "sales-returns",
      "Sales Returns",
      "Review credit notes and returned sales transactions.",
      "/sales/credit-notes",
      "Sales",
      FileBarChart,
    ),
  ],
  reportingInformation:
    "Sales reports use posted sales transactions and update as orders, invoices, and payments are posted.",
  accent: "blue",
};

export const purchasesReportsConfig: ReportsListingConfig = {
  module: "purchases",
  title: "Purchases Reports",
  description: "Analyze purchasing activity, supplier performance and accounts payable.",
  categories: ["All", "Purchasing", "Suppliers", "Payables", "Products"],
  kpis: [
    {
      label: "Purchases YTD",
      value: null,
      tone: "bg-orange-500/10 text-orange-700",
      icon: ShoppingCart,
    },
    {
      label: "Purchase Orders",
      value: null,
      suffix: "orders",
      tone: "bg-blue-500/10 text-blue-700",
      icon: FileBarChart,
    },
    {
      label: "Outstanding Payables",
      value: null,
      tone: "bg-rose-500/10 text-rose-700",
      icon: WalletCards,
    },
    {
      label: "Supplier Count",
      value: null,
      suffix: "suppliers",
      tone: "bg-violet-500/10 text-violet-700",
      icon: Users,
    },
  ],
  reports: [
    row(
      "purchase-summary",
      "Purchase Summary",
      "Review purchasing activity and posted supplier spend.",
      "/purchasing/orders",
      "Purchasing",
      ShoppingCart,
      "bg-orange-500/10 text-orange-700",
    ),
    row(
      "supplier-performance",
      "Supplier Performance",
      "Review supplier activity, orders, and delivery context.",
      "/purchasing/suppliers",
      "Suppliers",
      Store,
      "bg-orange-500/10 text-orange-700",
    ),
    row(
      "accounts-payable",
      "Accounts Payable",
      "Review supplier balances, bills, and outstanding payments.",
      "/purchasing/bills",
      "Payables",
      WalletCards,
      "bg-orange-500/10 text-orange-700",
    ),
    row(
      "supplier-spend",
      "Supplier Spend Analysis",
      "Compare purchasing spend across supplier records.",
      "/purchasing/suppliers",
      "Suppliers",
      Users,
      "bg-orange-500/10 text-orange-700",
    ),
    row(
      "purchase-expenses",
      "Expense Report",
      "Review operational expenses and their posting status.",
      "/purchasing/expenses",
      "Purchasing",
      FileBarChart,
      "bg-orange-500/10 text-orange-700",
    ),
  ],
  reportingInformation:
    "Purchasing reports use current tenant purchasing records and posted accounting transactions where available.",
  accent: "orange",
};

export const inventoryReportsConfig: ReportsListingConfig = {
  module: "inventory",
  title: "Inventory Reports",
  description: "Monitor stock levels, movements, valuation and warehouse performance.",
  categories: ["All", "Stock", "Warehouses", "Valuation", "Movement"],
  kpis: [
    { label: "Inventory Value", value: null, tone: "bg-cyan-500/10 text-cyan-700", icon: Boxes },
    {
      label: "Stock On Hand",
      value: null,
      suffix: "units",
      tone: "bg-blue-500/10 text-blue-700",
      icon: Package,
    },
    {
      label: "Low Stock Items",
      value: null,
      suffix: "items",
      tone: "bg-orange-500/10 text-orange-700",
      icon: FileBarChart,
    },
    {
      label: "Stock Movements",
      value: null,
      suffix: "movements",
      tone: "bg-teal-500/10 text-teal-700",
      icon: BarChart3,
    },
  ],
  reports: [
    row(
      "inventory-summary",
      "Inventory Summary",
      "Review current inventory position across the tenant.",
      "/inventory/items",
      "Stock",
      Boxes,
      "bg-cyan-500/10 text-cyan-700",
    ),
    row(
      "stock-on-hand",
      "Stock on Hand",
      "Review available quantities by item and location.",
      "/inventory/locations",
      "Stock",
      Package,
      "bg-cyan-500/10 text-cyan-700",
    ),
    row(
      "stock-movement",
      "Stock Movement",
      "Review inventory receipts, issues, and adjustments.",
      "/inventory/ledger",
      "Movement",
      BarChart3,
      "bg-cyan-500/10 text-cyan-700",
    ),
    row(
      "stock-adjustments",
      "Stock Adjustment Report",
      "Review adjustment transactions and their reasons.",
      "/inventory/adjustments",
      "Movement",
      FileBarChart,
      "bg-cyan-500/10 text-cyan-700",
    ),
    row(
      "stock-transfers",
      "Stock Transfer Report",
      "Review transfers between inventory locations.",
      "/inventory/transfers",
      "Movement",
      Store,
      "bg-cyan-500/10 text-cyan-700",
    ),
  ],
  reportingInformation:
    "Inventory reports are based on current stock, movement, location, and adjustment records for the active tenant.",
  accent: "cyan",
};

export const manufacturingReportsConfig: ReportsListingConfig = {
  module: "manufacturing",
  title: "Manufacturing Reports",
  description: "Monitor production, material consumption, costs and manufacturing performance.",
  categories: ["All", "Production", "Materials", "Costs", "Efficiency"],
  kpis: [
    {
      label: "Production YTD",
      value: null,
      tone: "bg-indigo-500/10 text-indigo-700",
      icon: Factory,
    },
    {
      label: "Production Orders",
      value: null,
      suffix: "orders",
      tone: "bg-violet-500/10 text-violet-700",
      icon: FileBarChart,
    },
    {
      label: "Production Cost",
      value: null,
      tone: "bg-purple-500/10 text-purple-700",
      icon: WalletCards,
    },
    {
      label: "Material Variance",
      value: null,
      tone: "bg-orange-500/10 text-orange-700",
      icon: BarChart3,
    },
  ],
  reports: [
    row(
      "production-summary",
      "Production Summary",
      "Review production order activity and completion context.",
      "/manufacturing/orders",
      "Production",
      Factory,
      "bg-indigo-500/10 text-indigo-700",
    ),
    row(
      "production-orders",
      "Production Order Report",
      "Review production orders and their current statuses.",
      "/manufacturing/orders",
      "Production",
      FileBarChart,
      "bg-indigo-500/10 text-indigo-700",
    ),
    row(
      "material-consumption",
      "Material Consumption",
      "Review component and material consumption by production.",
      "/manufacturing/bom",
      "Materials",
      Boxes,
      "bg-indigo-500/10 text-indigo-700",
    ),
    row(
      "production-cost",
      "Production Cost",
      "Review production cost context for manufactured output.",
      "/manufacturing/orders",
      "Costs",
      WalletCards,
      "bg-indigo-500/10 text-indigo-700",
    ),
    row(
      "production-efficiency",
      "Production Efficiency",
      "Review production progress and efficiency indicators.",
      "/manufacturing/runs",
      "Efficiency",
      BarChart3,
      "bg-indigo-500/10 text-indigo-700",
    ),
  ],
  reportingInformation:
    "Manufacturing reports use production orders, bills of material, runs, and related inventory records.",
  accent: "indigo",
};
