import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { db } from "@/lib/typed-db";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { SupplierBillDialog } from "@/components/supplier-bill-dialog";

export function SupplierBillListPage() {
  const [open, setOpen] = useState(false); const [status, setStatus] = useState("all"); const [supplierId, setSupplierId] = useState("all"); const [search, setSearch] = useState("");
  const { data: suppliers = [] } = useQuery({ queryKey: ["suppliers", "bill-filter"], queryFn: async () => { const { data, error } = await db.from("suppliers").select("id,name").is("deleted_at", null).order("name"); if (error) throw error; return (data ?? []) as Record<string, any>[]; } });
  const { data: bills = [], isLoading } = useQuery({ queryKey: ["bills", "ap-list", status, supplierId, search], queryFn: async () => { let query = db.from("bills").select("id,number,supplier_invoice_number,supplier_id,date,due_date,currency,grand_total,status,source_po_id,posted_at").is("deleted_at", null).order("date", { ascending: false }); if (status !== "all") query = query.eq("status", status); if (supplierId !== "all") query = query.eq("supplier_id", supplierId); if (search.trim()) query = query.or(`number.ilike.%${search.trim()}%,supplier_invoice_number.ilike.%${search.trim()}%`); const { data, error } = await query; if (error) throw error; return (data ?? []) as Record<string, any>[]; } });
  const supplierMap = Object.fromEntries(suppliers.map((supplier) => [supplier.id, supplier.name]));
  return <div className="h-full overflow-auto bg-background p-6"><div className="mx-auto max-w-7xl space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-xl font-semibold">Supplier Bills</h1><p className="text-sm text-muted-foreground">Accounts payable documents, matching, approvals, and payment status.</p></div><Button onClick={() => setOpen(true)}>New Bill</Button></div><div className="flex flex-wrap gap-2"><Input className="w-64" placeholder="Search bill or supplier invoice #" value={search} onChange={(event) => setSearch(event.target.value)} /><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-44"><SelectValue placeholder="Status" /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{["Draft", "Pending Approval", "Approved", "Posted", "Partially Paid", "Paid", "Overdue", "Voided", "Cancelled"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><Select value={supplierId} onValueChange={setSupplierId}><SelectTrigger className="w-52"><SelectValue placeholder="Supplier" /></SelectTrigger><SelectContent><SelectItem value="all">All suppliers</SelectItem>{suppliers.map((supplier) => <SelectItem key={supplier.id} value={supplier.id}>{supplier.name}</SelectItem>)}</SelectContent></Select></div><Card className="overflow-hidden"><table className="w-full text-sm"><thead className="bg-muted/50 text-left text-xs text-muted-foreground"><tr><th className="p-3">Bill Number</th><th className="p-3">Supplier</th><th className="p-3">Supplier Invoice #</th><th className="p-3">Bill Date</th><th className="p-3">Due Date</th><th className="p-3 text-right">Total</th><th className="p-3">Status</th><th className="p-3">PO</th></tr></thead><tbody>{isLoading ? <tr><td colSpan={8} className="p-8 text-center">Loading...</td></tr> : bills.map((bill) => <tr className="border-t" key={bill.id}><td className="p-3"><Link className="text-primary hover:underline" to="/purchasing/bills/$id" params={{ id: bill.id }}>{bill.number ?? bill.id.slice(0, 8)}</Link></td><td className="p-3">{supplierMap[bill.supplier_id] ?? "—"}</td><td className="p-3 font-mono text-xs">{bill.supplier_invoice_number ?? "—"}</td><td className="p-3">{bill.date ?? "—"}</td><td className="p-3">{bill.due_date ?? "—"}</td><td className="p-3 text-right font-mono">{bill.currency} {Number(bill.grand_total ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td><td className="p-3">{bill.status}</td><td className="p-3 font-mono text-xs">{bill.source_po_id ?? "—"}</td></tr>)}</tbody></table></Card></div><SupplierBillDialog open={open} onOpenChange={setOpen} onCreated={(id) => { window.location.assign(`/purchasing/bills/${id}`); }} /></div>;
}