import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { db } from "@/lib/typed-db";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export function SupplierBillDialog({ open, onOpenChange, onCreated }: { open: boolean; onOpenChange: (open: boolean) => void; onCreated?: (id: string) => void }) {
  const [supplierId, setSupplierId] = useState(""); const [invoiceNumber, setInvoiceNumber] = useState(""); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [dueDate, setDueDate] = useState(""); const [currency, setCurrency] = useState("KES"); const [description, setDescription] = useState(""); const [quantity, setQuantity] = useState("1"); const [unitPrice, setUnitPrice] = useState("");
  const { data: suppliers = [] } = useQuery({ queryKey: ["suppliers", "bill-dialog"], enabled: open, queryFn: async () => { const { data, error } = await db.from("suppliers").select("id,name,currency").is("deleted_at", null).order("name"); if (error) throw error; return (data ?? []) as Record<string, any>[]; } });
  const submit = async () => { const qty = Number(quantity); const price = Number(unitPrice); if (!supplierId) return toast.error("Select a supplier"); if (!Number.isFinite(qty) || qty <= 0 || !Number.isFinite(price) || price < 0) return toast.error("Enter a valid quantity and price"); const { data, error } = await db.rpc("create_supplier_bill", { _supplier_id: supplierId, _date: date, _due_date: dueDate || null, _currency: currency, _supplier_invoice_number: invoiceNumber || null, _lines: [{ description, quantity: qty, unit_price: price, discount_pct: 0, tax_pct: 0 }] }); if (error) return toast.error(error.message); toast.success("Supplier bill created as Draft"); onOpenChange(false); onCreated?.(String(data)); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>New Supplier Bill</DialogTitle></DialogHeader><div className="grid gap-4"><div className="grid gap-1.5"><Label>Supplier</Label><Select value={supplierId} onValueChange={(value) => { setSupplierId(value); const supplier = suppliers.find((row) => row.id === value); if (supplier?.currency) setCurrency(supplier.currency); }}><SelectTrigger><SelectValue placeholder="Select supplier" /></SelectTrigger><SelectContent>{suppliers.map((supplier) => <SelectItem key={supplier.id} value={supplier.id}>{supplier.name}</SelectItem>)}</SelectContent></Select></div><div className="grid grid-cols-2 gap-3"><div className="grid gap-1.5"><Label>Supplier Invoice #</Label><Input value={invoiceNumber} onChange={(event) => setInvoiceNumber(event.target.value)} /></div><div className="grid gap-1.5"><Label>Currency</Label><Input value={currency} onChange={(event) => setCurrency(event.target.value.toUpperCase())} maxLength={3} /></div></div><div className="grid grid-cols-2 gap-3"><div className="grid gap-1.5"><Label>Bill Date</Label><Input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></div><div className="grid gap-1.5"><Label>Due Date</Label><Input type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} /></div></div><div className="grid gap-1.5"><Label>Description</Label><Textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={2} /></div><div className="grid grid-cols-2 gap-3"><div className="grid gap-1.5"><Label>Quantity</Label><Input type="number" min="0.01" step="0.01" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></div><div className="grid gap-1.5"><Label>Unit Price</Label><Input type="number" min="0" step="0.01" value={unitPrice} onChange={(event) => setUnitPrice(event.target.value)} /></div></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={submit}>Create Draft</Button></DialogFooter></DialogContent></Dialog>;
}