/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSuperAdminUsersRouteImport } from './routes/_authenticated/super-admin.users'
import { Route as AuthenticatedSuperAdminTenantsRouteImport } from './routes/_authenticated/super-admin.tenants'
import { Route as AuthenticatedSuperAdminSettingsRouteImport } from './routes/_authenticated/super-admin.settings'
import { Route as AuthenticatedSuperAdminPlansRouteImport } from './routes/_authenticated/super-admin.plans'
import { Route as AuthenticatedSuperAdminAuditRouteImport } from './routes/_authenticated/super-admin.audit'
import { Route as AuthenticatedSettingsWorkflowsRouteImport } from './routes/_authenticated/settings.workflows'
import { Route as AuthenticatedSettingsWarehousesRouteImport } from './routes/_authenticated/settings.warehouses'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedSettingsUomRouteImport } from './routes/_authenticated/settings.uom'
import { Route as AuthenticatedSettingsTemplatesRouteImport } from './routes/_authenticated/settings.templates'
import { Route as AuthenticatedSettingsTaxesRouteImport } from './routes/_authenticated/settings.taxes'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings.roles'
import { Route as AuthenticatedSettingsPaymentTermsRouteImport } from './routes/_authenticated/settings.payment-terms'
import { Route as AuthenticatedSettingsNumberingRouteImport } from './routes/_authenticated/settings.numbering'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedSettingsCurrenciesRouteImport } from './routes/_authenticated/settings.currencies'
import { Route as AuthenticatedSettingsCompanyRouteImport } from './routes/_authenticated/settings.company'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings.api-keys'
import { Route as AuthenticatedSalesShipmentsRouteImport } from './routes/_authenticated/sales.shipments'
import { Route as AuthenticatedSalesQuotesRouteImport } from './routes/_authenticated/sales.quotes'
import { Route as AuthenticatedSalesPaymentsRouteImport } from './routes/_authenticated/sales.payments'
import { Route as AuthenticatedSalesPackagesRouteImport } from './routes/_authenticated/sales.packages'
import { Route as AuthenticatedSalesOrdersRouteImport } from './routes/_authenticated/sales.orders'
import { Route as AuthenticatedSalesInvoicesRouteImport } from './routes/_authenticated/sales.invoices'
import { Route as AuthenticatedSalesCreditNotesRouteImport } from './routes/_authenticated/sales.credit-notes'
import { Route as AuthenticatedReportsSalesRouteImport } from './routes/_authenticated/reports.sales'
import { Route as AuthenticatedReportsPurchasesRouteImport } from './routes/_authenticated/reports.purchases'
import { Route as AuthenticatedReportsManufacturingRouteImport } from './routes/_authenticated/reports.manufacturing'
import { Route as AuthenticatedReportsInventoryRouteImport } from './routes/_authenticated/reports.inventory'
import { Route as AuthenticatedReportsFinancialRouteImport } from './routes/_authenticated/reports.financial'
import { Route as AuthenticatedPurchasingSuppliersRouteImport } from './routes/_authenticated/purchasing.suppliers'
import { Route as AuthenticatedPurchasingRequisitionsRouteImport } from './routes/_authenticated/purchasing.requisitions'
import { Route as AuthenticatedPurchasingPaymentsRouteImport } from './routes/_authenticated/purchasing.payments'
import { Route as AuthenticatedPurchasingOrdersRouteImport } from './routes/_authenticated/purchasing.orders'
import { Route as AuthenticatedPurchasingExpensesRouteImport } from './routes/_authenticated/purchasing.expenses'
import { Route as AuthenticatedPurchasingCreditsRouteImport } from './routes/_authenticated/purchasing.credits'
import { Route as AuthenticatedPurchasingBillsRouteImport } from './routes/_authenticated/purchasing.bills'
import { Route as AuthenticatedManufacturingRunsRouteImport } from './routes/_authenticated/manufacturing.runs'
import { Route as AuthenticatedManufacturingOrdersRouteImport } from './routes/_authenticated/manufacturing.orders'
import { Route as AuthenticatedManufacturingItemsRouteImport } from './routes/_authenticated/manufacturing.items'
import { Route as AuthenticatedManufacturingBomRouteImport } from './routes/_authenticated/manufacturing.bom'
import { Route as AuthenticatedInventoryWarehousesRouteImport } from './routes/_authenticated/inventory.warehouses'
import { Route as AuthenticatedInventoryTransfersRouteImport } from './routes/_authenticated/inventory.transfers'
import { Route as AuthenticatedInventoryLedgerRouteImport } from './routes/_authenticated/inventory.ledger'
import { Route as AuthenticatedInventoryItemsRouteImport } from './routes/_authenticated/inventory.items'
import { Route as AuthenticatedInventoryAdjustmentsRouteImport } from './routes/_authenticated/inventory.adjustments'
import { Route as AuthenticatedDashboardsSalesRouteImport } from './routes/_authenticated/dashboards.sales'
import { Route as AuthenticatedDashboardsProductionRouteImport } from './routes/_authenticated/dashboards.production'
import { Route as AuthenticatedDashboardsProcurementRouteImport } from './routes/_authenticated/dashboards.procurement'
import { Route as AuthenticatedDashboardsLogisticsRouteImport } from './routes/_authenticated/dashboards.logistics'
import { Route as AuthenticatedCrmCustomersRouteImport } from './routes/_authenticated/crm.customers'
import { Route as AuthenticatedAccountingReconciliationRouteImport } from './routes/_authenticated/accounting.reconciliation'
import { Route as AuthenticatedAccountingJournalsRouteImport } from './routes/_authenticated/accounting.journals'
import { Route as AuthenticatedAccountingChartRouteImport } from './routes/_authenticated/accounting.chart'
import { Route as AuthenticatedAccountingBankingRouteImport } from './routes/_authenticated/accounting.banking'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperAdminUsersRoute =
  AuthenticatedSuperAdminUsersRouteImport.update({
    id: '/_authenticated/super-admin/users',
    path: '/super-admin/users',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSuperAdminTenantsRoute =
  AuthenticatedSuperAdminTenantsRouteImport.update({
    id: '/_authenticated/super-admin/tenants',
    path: '/super-admin/tenants',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSuperAdminSettingsRoute =
  AuthenticatedSuperAdminSettingsRouteImport.update({
    id: '/_authenticated/super-admin/settings',
    path: '/super-admin/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSuperAdminPlansRoute =
  AuthenticatedSuperAdminPlansRouteImport.update({
    id: '/_authenticated/super-admin/plans',
    path: '/super-admin/plans',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSuperAdminAuditRoute =
  AuthenticatedSuperAdminAuditRouteImport.update({
    id: '/_authenticated/super-admin/audit',
    path: '/super-admin/audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsWorkflowsRoute =
  AuthenticatedSettingsWorkflowsRouteImport.update({
    id: '/_authenticated/settings/workflows',
    path: '/settings/workflows',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsWarehousesRoute =
  AuthenticatedSettingsWarehousesRouteImport.update({
    id: '/_authenticated/settings/warehouses',
    path: '/settings/warehouses',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/_authenticated/settings/users',
    path: '/settings/users',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsUomRoute =
  AuthenticatedSettingsUomRouteImport.update({
    id: '/_authenticated/settings/uom',
    path: '/settings/uom',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsTemplatesRoute =
  AuthenticatedSettingsTemplatesRouteImport.update({
    id: '/_authenticated/settings/templates',
    path: '/settings/templates',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsTaxesRoute =
  AuthenticatedSettingsTaxesRouteImport.update({
    id: '/_authenticated/settings/taxes',
    path: '/settings/taxes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/_authenticated/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsPaymentTermsRoute =
  AuthenticatedSettingsPaymentTermsRouteImport.update({
    id: '/_authenticated/settings/payment-terms',
    path: '/settings/payment-terms',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsNumberingRoute =
  AuthenticatedSettingsNumberingRouteImport.update({
    id: '/_authenticated/settings/numbering',
    path: '/settings/numbering',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/_authenticated/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsCurrenciesRoute =
  AuthenticatedSettingsCurrenciesRouteImport.update({
    id: '/_authenticated/settings/currencies',
    path: '/settings/currencies',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsCompanyRoute =
  AuthenticatedSettingsCompanyRouteImport.update({
    id: '/_authenticated/settings/company',
    path: '/settings/company',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/_authenticated/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSalesShipmentsRoute =
  AuthenticatedSalesShipmentsRouteImport.update({
    id: '/_authenticated/sales/shipments',
    path: '/sales/shipments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSalesQuotesRoute =
  AuthenticatedSalesQuotesRouteImport.update({
    id: '/_authenticated/sales/quotes',
    path: '/sales/quotes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSalesPaymentsRoute =
  AuthenticatedSalesPaymentsRouteImport.update({
    id: '/_authenticated/sales/payments',
    path: '/sales/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSalesPackagesRoute =
  AuthenticatedSalesPackagesRouteImport.update({
    id: '/_authenticated/sales/packages',
    path: '/sales/packages',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSalesOrdersRoute =
  AuthenticatedSalesOrdersRouteImport.update({
    id: '/_authenticated/sales/orders',
    path: '/sales/orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSalesInvoicesRoute =
  AuthenticatedSalesInvoicesRouteImport.update({
    id: '/_authenticated/sales/invoices',
    path: '/sales/invoices',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSalesCreditNotesRoute =
  AuthenticatedSalesCreditNotesRouteImport.update({
    id: '/_authenticated/sales/credit-notes',
    path: '/sales/credit-notes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReportsSalesRoute =
  AuthenticatedReportsSalesRouteImport.update({
    id: '/_authenticated/reports/sales',
    path: '/reports/sales',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReportsPurchasesRoute =
  AuthenticatedReportsPurchasesRouteImport.update({
    id: '/_authenticated/reports/purchases',
    path: '/reports/purchases',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReportsManufacturingRoute =
  AuthenticatedReportsManufacturingRouteImport.update({
    id: '/_authenticated/reports/manufacturing',
    path: '/reports/manufacturing',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReportsInventoryRoute =
  AuthenticatedReportsInventoryRouteImport.update({
    id: '/_authenticated/reports/inventory',
    path: '/reports/inventory',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReportsFinancialRoute =
  AuthenticatedReportsFinancialRouteImport.update({
    id: '/_authenticated/reports/financial',
    path: '/reports/financial',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPurchasingSuppliersRoute =
  AuthenticatedPurchasingSuppliersRouteImport.update({
    id: '/_authenticated/purchasing/suppliers',
    path: '/purchasing/suppliers',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPurchasingRequisitionsRoute =
  AuthenticatedPurchasingRequisitionsRouteImport.update({
    id: '/_authenticated/purchasing/requisitions',
    path: '/purchasing/requisitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPurchasingPaymentsRoute =
  AuthenticatedPurchasingPaymentsRouteImport.update({
    id: '/_authenticated/purchasing/payments',
    path: '/purchasing/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPurchasingOrdersRoute =
  AuthenticatedPurchasingOrdersRouteImport.update({
    id: '/_authenticated/purchasing/orders',
    path: '/purchasing/orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPurchasingExpensesRoute =
  AuthenticatedPurchasingExpensesRouteImport.update({
    id: '/_authenticated/purchasing/expenses',
    path: '/purchasing/expenses',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPurchasingCreditsRoute =
  AuthenticatedPurchasingCreditsRouteImport.update({
    id: '/_authenticated/purchasing/credits',
    path: '/purchasing/credits',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPurchasingBillsRoute =
  AuthenticatedPurchasingBillsRouteImport.update({
    id: '/_authenticated/purchasing/bills',
    path: '/purchasing/bills',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedManufacturingRunsRoute =
  AuthenticatedManufacturingRunsRouteImport.update({
    id: '/_authenticated/manufacturing/runs',
    path: '/manufacturing/runs',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedManufacturingOrdersRoute =
  AuthenticatedManufacturingOrdersRouteImport.update({
    id: '/_authenticated/manufacturing/orders',
    path: '/manufacturing/orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedManufacturingItemsRoute =
  AuthenticatedManufacturingItemsRouteImport.update({
    id: '/_authenticated/manufacturing/items',
    path: '/manufacturing/items',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedManufacturingBomRoute =
  AuthenticatedManufacturingBomRouteImport.update({
    id: '/_authenticated/manufacturing/bom',
    path: '/manufacturing/bom',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInventoryWarehousesRoute =
  AuthenticatedInventoryWarehousesRouteImport.update({
    id: '/_authenticated/inventory/warehouses',
    path: '/inventory/warehouses',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInventoryTransfersRoute =
  AuthenticatedInventoryTransfersRouteImport.update({
    id: '/_authenticated/inventory/transfers',
    path: '/inventory/transfers',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInventoryLedgerRoute =
  AuthenticatedInventoryLedgerRouteImport.update({
    id: '/_authenticated/inventory/ledger',
    path: '/inventory/ledger',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInventoryItemsRoute =
  AuthenticatedInventoryItemsRouteImport.update({
    id: '/_authenticated/inventory/items',
    path: '/inventory/items',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInventoryAdjustmentsRoute =
  AuthenticatedInventoryAdjustmentsRouteImport.update({
    id: '/_authenticated/inventory/adjustments',
    path: '/inventory/adjustments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardsSalesRoute =
  AuthenticatedDashboardsSalesRouteImport.update({
    id: '/_authenticated/dashboards/sales',
    path: '/dashboards/sales',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardsProductionRoute =
  AuthenticatedDashboardsProductionRouteImport.update({
    id: '/_authenticated/dashboards/production',
    path: '/dashboards/production',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardsProcurementRoute =
  AuthenticatedDashboardsProcurementRouteImport.update({
    id: '/_authenticated/dashboards/procurement',
    path: '/dashboards/procurement',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardsLogisticsRoute =
  AuthenticatedDashboardsLogisticsRouteImport.update({
    id: '/_authenticated/dashboards/logistics',
    path: '/dashboards/logistics',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCrmCustomersRoute =
  AuthenticatedCrmCustomersRouteImport.update({
    id: '/_authenticated/crm/customers',
    path: '/crm/customers',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountingReconciliationRoute =
  AuthenticatedAccountingReconciliationRouteImport.update({
    id: '/_authenticated/accounting/reconciliation',
    path: '/accounting/reconciliation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountingJournalsRoute =
  AuthenticatedAccountingJournalsRouteImport.update({
    id: '/_authenticated/accounting/journals',
    path: '/accounting/journals',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountingChartRoute =
  AuthenticatedAccountingChartRouteImport.update({
    id: '/_authenticated/accounting/chart',
    path: '/accounting/chart',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountingBankingRoute =
  AuthenticatedAccountingBankingRouteImport.update({
    id: '/_authenticated/accounting/banking',
    path: '/accounting/banking',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accounting/banking': typeof AuthenticatedAccountingBankingRoute
  '/accounting/chart': typeof AuthenticatedAccountingChartRoute
  '/accounting/journals': typeof AuthenticatedAccountingJournalsRoute
  '/accounting/reconciliation': typeof AuthenticatedAccountingReconciliationRoute
  '/crm/customers': typeof AuthenticatedCrmCustomersRoute
  '/dashboards/logistics': typeof AuthenticatedDashboardsLogisticsRoute
  '/dashboards/procurement': typeof AuthenticatedDashboardsProcurementRoute
  '/dashboards/production': typeof AuthenticatedDashboardsProductionRoute
  '/dashboards/sales': typeof AuthenticatedDashboardsSalesRoute
  '/inventory/adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/inventory/items': typeof AuthenticatedInventoryItemsRoute
  '/inventory/ledger': typeof AuthenticatedInventoryLedgerRoute
  '/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/inventory/warehouses': typeof AuthenticatedInventoryWarehousesRoute
  '/manufacturing/bom': typeof AuthenticatedManufacturingBomRoute
  '/manufacturing/items': typeof AuthenticatedManufacturingItemsRoute
  '/manufacturing/orders': typeof AuthenticatedManufacturingOrdersRoute
  '/manufacturing/runs': typeof AuthenticatedManufacturingRunsRoute
  '/purchasing/bills': typeof AuthenticatedPurchasingBillsRoute
  '/purchasing/credits': typeof AuthenticatedPurchasingCreditsRoute
  '/purchasing/expenses': typeof AuthenticatedPurchasingExpensesRoute
  '/purchasing/orders': typeof AuthenticatedPurchasingOrdersRoute
  '/purchasing/payments': typeof AuthenticatedPurchasingPaymentsRoute
  '/purchasing/requisitions': typeof AuthenticatedPurchasingRequisitionsRoute
  '/purchasing/suppliers': typeof AuthenticatedPurchasingSuppliersRoute
  '/reports/financial': typeof AuthenticatedReportsFinancialRoute
  '/reports/inventory': typeof AuthenticatedReportsInventoryRoute
  '/reports/manufacturing': typeof AuthenticatedReportsManufacturingRoute
  '/reports/purchases': typeof AuthenticatedReportsPurchasesRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/sales/credit-notes': typeof AuthenticatedSalesCreditNotesRoute
  '/sales/invoices': typeof AuthenticatedSalesInvoicesRoute
  '/sales/orders': typeof AuthenticatedSalesOrdersRoute
  '/sales/packages': typeof AuthenticatedSalesPackagesRoute
  '/sales/payments': typeof AuthenticatedSalesPaymentsRoute
  '/sales/quotes': typeof AuthenticatedSalesQuotesRoute
  '/sales/shipments': typeof AuthenticatedSalesShipmentsRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/numbering': typeof AuthenticatedSettingsNumberingRoute
  '/settings/payment-terms': typeof AuthenticatedSettingsPaymentTermsRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/taxes': typeof AuthenticatedSettingsTaxesRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/settings/uom': typeof AuthenticatedSettingsUomRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/warehouses': typeof AuthenticatedSettingsWarehousesRoute
  '/settings/workflows': typeof AuthenticatedSettingsWorkflowsRoute
  '/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/super-admin/plans': typeof AuthenticatedSuperAdminPlansRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/tenants': typeof AuthenticatedSuperAdminTenantsRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/accounting/banking': typeof AuthenticatedAccountingBankingRoute
  '/accounting/chart': typeof AuthenticatedAccountingChartRoute
  '/accounting/journals': typeof AuthenticatedAccountingJournalsRoute
  '/accounting/reconciliation': typeof AuthenticatedAccountingReconciliationRoute
  '/crm/customers': typeof AuthenticatedCrmCustomersRoute
  '/dashboards/logistics': typeof AuthenticatedDashboardsLogisticsRoute
  '/dashboards/procurement': typeof AuthenticatedDashboardsProcurementRoute
  '/dashboards/production': typeof AuthenticatedDashboardsProductionRoute
  '/dashboards/sales': typeof AuthenticatedDashboardsSalesRoute
  '/inventory/adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/inventory/items': typeof AuthenticatedInventoryItemsRoute
  '/inventory/ledger': typeof AuthenticatedInventoryLedgerRoute
  '/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/inventory/warehouses': typeof AuthenticatedInventoryWarehousesRoute
  '/manufacturing/bom': typeof AuthenticatedManufacturingBomRoute
  '/manufacturing/items': typeof AuthenticatedManufacturingItemsRoute
  '/manufacturing/orders': typeof AuthenticatedManufacturingOrdersRoute
  '/manufacturing/runs': typeof AuthenticatedManufacturingRunsRoute
  '/purchasing/bills': typeof AuthenticatedPurchasingBillsRoute
  '/purchasing/credits': typeof AuthenticatedPurchasingCreditsRoute
  '/purchasing/expenses': typeof AuthenticatedPurchasingExpensesRoute
  '/purchasing/orders': typeof AuthenticatedPurchasingOrdersRoute
  '/purchasing/payments': typeof AuthenticatedPurchasingPaymentsRoute
  '/purchasing/requisitions': typeof AuthenticatedPurchasingRequisitionsRoute
  '/purchasing/suppliers': typeof AuthenticatedPurchasingSuppliersRoute
  '/reports/financial': typeof AuthenticatedReportsFinancialRoute
  '/reports/inventory': typeof AuthenticatedReportsInventoryRoute
  '/reports/manufacturing': typeof AuthenticatedReportsManufacturingRoute
  '/reports/purchases': typeof AuthenticatedReportsPurchasesRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/sales/credit-notes': typeof AuthenticatedSalesCreditNotesRoute
  '/sales/invoices': typeof AuthenticatedSalesInvoicesRoute
  '/sales/orders': typeof AuthenticatedSalesOrdersRoute
  '/sales/packages': typeof AuthenticatedSalesPackagesRoute
  '/sales/payments': typeof AuthenticatedSalesPaymentsRoute
  '/sales/quotes': typeof AuthenticatedSalesQuotesRoute
  '/sales/shipments': typeof AuthenticatedSalesShipmentsRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/numbering': typeof AuthenticatedSettingsNumberingRoute
  '/settings/payment-terms': typeof AuthenticatedSettingsPaymentTermsRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/taxes': typeof AuthenticatedSettingsTaxesRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/settings/uom': typeof AuthenticatedSettingsUomRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/warehouses': typeof AuthenticatedSettingsWarehousesRoute
  '/settings/workflows': typeof AuthenticatedSettingsWorkflowsRoute
  '/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/super-admin/plans': typeof AuthenticatedSuperAdminPlansRoute
  '/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/super-admin/tenants': typeof AuthenticatedSuperAdminTenantsRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/accounting/banking': typeof AuthenticatedAccountingBankingRoute
  '/_authenticated/accounting/chart': typeof AuthenticatedAccountingChartRoute
  '/_authenticated/accounting/journals': typeof AuthenticatedAccountingJournalsRoute
  '/_authenticated/accounting/reconciliation': typeof AuthenticatedAccountingReconciliationRoute
  '/_authenticated/crm/customers': typeof AuthenticatedCrmCustomersRoute
  '/_authenticated/dashboards/logistics': typeof AuthenticatedDashboardsLogisticsRoute
  '/_authenticated/dashboards/procurement': typeof AuthenticatedDashboardsProcurementRoute
  '/_authenticated/dashboards/production': typeof AuthenticatedDashboardsProductionRoute
  '/_authenticated/dashboards/sales': typeof AuthenticatedDashboardsSalesRoute
  '/_authenticated/inventory/adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/_authenticated/inventory/items': typeof AuthenticatedInventoryItemsRoute
  '/_authenticated/inventory/ledger': typeof AuthenticatedInventoryLedgerRoute
  '/_authenticated/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/_authenticated/inventory/warehouses': typeof AuthenticatedInventoryWarehousesRoute
  '/_authenticated/manufacturing/bom': typeof AuthenticatedManufacturingBomRoute
  '/_authenticated/manufacturing/items': typeof AuthenticatedManufacturingItemsRoute
  '/_authenticated/manufacturing/orders': typeof AuthenticatedManufacturingOrdersRoute
  '/_authenticated/manufacturing/runs': typeof AuthenticatedManufacturingRunsRoute
  '/_authenticated/purchasing/bills': typeof AuthenticatedPurchasingBillsRoute
  '/_authenticated/purchasing/credits': typeof AuthenticatedPurchasingCreditsRoute
  '/_authenticated/purchasing/expenses': typeof AuthenticatedPurchasingExpensesRoute
  '/_authenticated/purchasing/orders': typeof AuthenticatedPurchasingOrdersRoute
  '/_authenticated/purchasing/payments': typeof AuthenticatedPurchasingPaymentsRoute
  '/_authenticated/purchasing/requisitions': typeof AuthenticatedPurchasingRequisitionsRoute
  '/_authenticated/purchasing/suppliers': typeof AuthenticatedPurchasingSuppliersRoute
  '/_authenticated/reports/financial': typeof AuthenticatedReportsFinancialRoute
  '/_authenticated/reports/inventory': typeof AuthenticatedReportsInventoryRoute
  '/_authenticated/reports/manufacturing': typeof AuthenticatedReportsManufacturingRoute
  '/_authenticated/reports/purchases': typeof AuthenticatedReportsPurchasesRoute
  '/_authenticated/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/_authenticated/sales/credit-notes': typeof AuthenticatedSalesCreditNotesRoute
  '/_authenticated/sales/invoices': typeof AuthenticatedSalesInvoicesRoute
  '/_authenticated/sales/orders': typeof AuthenticatedSalesOrdersRoute
  '/_authenticated/sales/packages': typeof AuthenticatedSalesPackagesRoute
  '/_authenticated/sales/payments': typeof AuthenticatedSalesPaymentsRoute
  '/_authenticated/sales/quotes': typeof AuthenticatedSalesQuotesRoute
  '/_authenticated/sales/shipments': typeof AuthenticatedSalesShipmentsRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/_authenticated/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/numbering': typeof AuthenticatedSettingsNumberingRoute
  '/_authenticated/settings/payment-terms': typeof AuthenticatedSettingsPaymentTermsRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/taxes': typeof AuthenticatedSettingsTaxesRoute
  '/_authenticated/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/_authenticated/settings/uom': typeof AuthenticatedSettingsUomRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/settings/warehouses': typeof AuthenticatedSettingsWarehousesRoute
  '/_authenticated/settings/workflows': typeof AuthenticatedSettingsWorkflowsRoute
  '/_authenticated/super-admin/audit': typeof AuthenticatedSuperAdminAuditRoute
  '/_authenticated/super-admin/plans': typeof AuthenticatedSuperAdminPlansRoute
  '/_authenticated/super-admin/settings': typeof AuthenticatedSuperAdminSettingsRoute
  '/_authenticated/super-admin/tenants': typeof AuthenticatedSuperAdminTenantsRoute
  '/_authenticated/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting/banking'
    | '/accounting/chart'
    | '/accounting/journals'
    | '/accounting/reconciliation'
    | '/crm/customers'
    | '/dashboards/logistics'
    | '/dashboards/procurement'
    | '/dashboards/production'
    | '/dashboards/sales'
    | '/inventory/adjustments'
    | '/inventory/items'
    | '/inventory/ledger'
    | '/inventory/transfers'
    | '/inventory/warehouses'
    | '/manufacturing/bom'
    | '/manufacturing/items'
    | '/manufacturing/orders'
    | '/manufacturing/runs'
    | '/purchasing/bills'
    | '/purchasing/credits'
    | '/purchasing/expenses'
    | '/purchasing/orders'
    | '/purchasing/payments'
    | '/purchasing/requisitions'
    | '/purchasing/suppliers'
    | '/reports/financial'
    | '/reports/inventory'
    | '/reports/manufacturing'
    | '/reports/purchases'
    | '/reports/sales'
    | '/sales/credit-notes'
    | '/sales/invoices'
    | '/sales/orders'
    | '/sales/packages'
    | '/sales/payments'
    | '/sales/quotes'
    | '/sales/shipments'
    | '/settings/api-keys'
    | '/settings/company'
    | '/settings/currencies'
    | '/settings/notifications'
    | '/settings/numbering'
    | '/settings/payment-terms'
    | '/settings/roles'
    | '/settings/taxes'
    | '/settings/templates'
    | '/settings/uom'
    | '/settings/users'
    | '/settings/warehouses'
    | '/settings/workflows'
    | '/super-admin/audit'
    | '/super-admin/plans'
    | '/super-admin/settings'
    | '/super-admin/tenants'
    | '/super-admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting/banking'
    | '/accounting/chart'
    | '/accounting/journals'
    | '/accounting/reconciliation'
    | '/crm/customers'
    | '/dashboards/logistics'
    | '/dashboards/procurement'
    | '/dashboards/production'
    | '/dashboards/sales'
    | '/inventory/adjustments'
    | '/inventory/items'
    | '/inventory/ledger'
    | '/inventory/transfers'
    | '/inventory/warehouses'
    | '/manufacturing/bom'
    | '/manufacturing/items'
    | '/manufacturing/orders'
    | '/manufacturing/runs'
    | '/purchasing/bills'
    | '/purchasing/credits'
    | '/purchasing/expenses'
    | '/purchasing/orders'
    | '/purchasing/payments'
    | '/purchasing/requisitions'
    | '/purchasing/suppliers'
    | '/reports/financial'
    | '/reports/inventory'
    | '/reports/manufacturing'
    | '/reports/purchases'
    | '/reports/sales'
    | '/sales/credit-notes'
    | '/sales/invoices'
    | '/sales/orders'
    | '/sales/packages'
    | '/sales/payments'
    | '/sales/quotes'
    | '/sales/shipments'
    | '/settings/api-keys'
    | '/settings/company'
    | '/settings/currencies'
    | '/settings/notifications'
    | '/settings/numbering'
    | '/settings/payment-terms'
    | '/settings/roles'
    | '/settings/taxes'
    | '/settings/templates'
    | '/settings/uom'
    | '/settings/users'
    | '/settings/warehouses'
    | '/settings/workflows'
    | '/super-admin/audit'
    | '/super-admin/plans'
    | '/super-admin/settings'
    | '/super-admin/tenants'
    | '/super-admin/users'
  id:
    | '__root__'
    | '/_authenticated/'
    | '/_authenticated/accounting/banking'
    | '/_authenticated/accounting/chart'
    | '/_authenticated/accounting/journals'
    | '/_authenticated/accounting/reconciliation'
    | '/_authenticated/crm/customers'
    | '/_authenticated/dashboards/logistics'
    | '/_authenticated/dashboards/procurement'
    | '/_authenticated/dashboards/production'
    | '/_authenticated/dashboards/sales'
    | '/_authenticated/inventory/adjustments'
    | '/_authenticated/inventory/items'
    | '/_authenticated/inventory/ledger'
    | '/_authenticated/inventory/transfers'
    | '/_authenticated/inventory/warehouses'
    | '/_authenticated/manufacturing/bom'
    | '/_authenticated/manufacturing/items'
    | '/_authenticated/manufacturing/orders'
    | '/_authenticated/manufacturing/runs'
    | '/_authenticated/purchasing/bills'
    | '/_authenticated/purchasing/credits'
    | '/_authenticated/purchasing/expenses'
    | '/_authenticated/purchasing/orders'
    | '/_authenticated/purchasing/payments'
    | '/_authenticated/purchasing/requisitions'
    | '/_authenticated/purchasing/suppliers'
    | '/_authenticated/reports/financial'
    | '/_authenticated/reports/inventory'
    | '/_authenticated/reports/manufacturing'
    | '/_authenticated/reports/purchases'
    | '/_authenticated/reports/sales'
    | '/_authenticated/sales/credit-notes'
    | '/_authenticated/sales/invoices'
    | '/_authenticated/sales/orders'
    | '/_authenticated/sales/packages'
    | '/_authenticated/sales/payments'
    | '/_authenticated/sales/quotes'
    | '/_authenticated/sales/shipments'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/company'
    | '/_authenticated/settings/currencies'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/numbering'
    | '/_authenticated/settings/payment-terms'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/taxes'
    | '/_authenticated/settings/templates'
    | '/_authenticated/settings/uom'
    | '/_authenticated/settings/users'
    | '/_authenticated/settings/warehouses'
    | '/_authenticated/settings/workflows'
    | '/_authenticated/super-admin/audit'
    | '/_authenticated/super-admin/plans'
    | '/_authenticated/super-admin/settings'
    | '/_authenticated/super-admin/tenants'
    | '/_authenticated/super-admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountingBankingRoute: typeof AuthenticatedAccountingBankingRoute
  AuthenticatedAccountingChartRoute: typeof AuthenticatedAccountingChartRoute
  AuthenticatedAccountingJournalsRoute: typeof AuthenticatedAccountingJournalsRoute
  AuthenticatedAccountingReconciliationRoute: typeof AuthenticatedAccountingReconciliationRoute
  AuthenticatedCrmCustomersRoute: typeof AuthenticatedCrmCustomersRoute
  AuthenticatedDashboardsLogisticsRoute: typeof AuthenticatedDashboardsLogisticsRoute
  AuthenticatedDashboardsProcurementRoute: typeof AuthenticatedDashboardsProcurementRoute
  AuthenticatedDashboardsProductionRoute: typeof AuthenticatedDashboardsProductionRoute
  AuthenticatedDashboardsSalesRoute: typeof AuthenticatedDashboardsSalesRoute
  AuthenticatedInventoryAdjustmentsRoute: typeof AuthenticatedInventoryAdjustmentsRoute
  AuthenticatedInventoryItemsRoute: typeof AuthenticatedInventoryItemsRoute
  AuthenticatedInventoryLedgerRoute: typeof AuthenticatedInventoryLedgerRoute
  AuthenticatedInventoryTransfersRoute: typeof AuthenticatedInventoryTransfersRoute
  AuthenticatedInventoryWarehousesRoute: typeof AuthenticatedInventoryWarehousesRoute
  AuthenticatedManufacturingBomRoute: typeof AuthenticatedManufacturingBomRoute
  AuthenticatedManufacturingItemsRoute: typeof AuthenticatedManufacturingItemsRoute
  AuthenticatedManufacturingOrdersRoute: typeof AuthenticatedManufacturingOrdersRoute
  AuthenticatedManufacturingRunsRoute: typeof AuthenticatedManufacturingRunsRoute
  AuthenticatedPurchasingBillsRoute: typeof AuthenticatedPurchasingBillsRoute
  AuthenticatedPurchasingCreditsRoute: typeof AuthenticatedPurchasingCreditsRoute
  AuthenticatedPurchasingExpensesRoute: typeof AuthenticatedPurchasingExpensesRoute
  AuthenticatedPurchasingOrdersRoute: typeof AuthenticatedPurchasingOrdersRoute
  AuthenticatedPurchasingPaymentsRoute: typeof AuthenticatedPurchasingPaymentsRoute
  AuthenticatedPurchasingRequisitionsRoute: typeof AuthenticatedPurchasingRequisitionsRoute
  AuthenticatedPurchasingSuppliersRoute: typeof AuthenticatedPurchasingSuppliersRoute
  AuthenticatedReportsFinancialRoute: typeof AuthenticatedReportsFinancialRoute
  AuthenticatedReportsInventoryRoute: typeof AuthenticatedReportsInventoryRoute
  AuthenticatedReportsManufacturingRoute: typeof AuthenticatedReportsManufacturingRoute
  AuthenticatedReportsPurchasesRoute: typeof AuthenticatedReportsPurchasesRoute
  AuthenticatedReportsSalesRoute: typeof AuthenticatedReportsSalesRoute
  AuthenticatedSalesCreditNotesRoute: typeof AuthenticatedSalesCreditNotesRoute
  AuthenticatedSalesInvoicesRoute: typeof AuthenticatedSalesInvoicesRoute
  AuthenticatedSalesOrdersRoute: typeof AuthenticatedSalesOrdersRoute
  AuthenticatedSalesPackagesRoute: typeof AuthenticatedSalesPackagesRoute
  AuthenticatedSalesPaymentsRoute: typeof AuthenticatedSalesPaymentsRoute
  AuthenticatedSalesQuotesRoute: typeof AuthenticatedSalesQuotesRoute
  AuthenticatedSalesShipmentsRoute: typeof AuthenticatedSalesShipmentsRoute
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsCompanyRoute: typeof AuthenticatedSettingsCompanyRoute
  AuthenticatedSettingsCurrenciesRoute: typeof AuthenticatedSettingsCurrenciesRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsNumberingRoute: typeof AuthenticatedSettingsNumberingRoute
  AuthenticatedSettingsPaymentTermsRoute: typeof AuthenticatedSettingsPaymentTermsRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsTaxesRoute: typeof AuthenticatedSettingsTaxesRoute
  AuthenticatedSettingsTemplatesRoute: typeof AuthenticatedSettingsTemplatesRoute
  AuthenticatedSettingsUomRoute: typeof AuthenticatedSettingsUomRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsWarehousesRoute: typeof AuthenticatedSettingsWarehousesRoute
  AuthenticatedSettingsWorkflowsRoute: typeof AuthenticatedSettingsWorkflowsRoute
  AuthenticatedSuperAdminAuditRoute: typeof AuthenticatedSuperAdminAuditRoute
  AuthenticatedSuperAdminPlansRoute: typeof AuthenticatedSuperAdminPlansRoute
  AuthenticatedSuperAdminSettingsRoute: typeof AuthenticatedSuperAdminSettingsRoute
  AuthenticatedSuperAdminTenantsRoute: typeof AuthenticatedSuperAdminTenantsRoute
  AuthenticatedSuperAdminUsersRoute: typeof AuthenticatedSuperAdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin/users': {
      id: '/_authenticated/super-admin/users'
      path: '/super-admin/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof AuthenticatedSuperAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin/tenants': {
      id: '/_authenticated/super-admin/tenants'
      path: '/super-admin/tenants'
      fullPath: '/super-admin/tenants'
      preLoaderRoute: typeof AuthenticatedSuperAdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin/settings': {
      id: '/_authenticated/super-admin/settings'
      path: '/super-admin/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof AuthenticatedSuperAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin/plans': {
      id: '/_authenticated/super-admin/plans'
      path: '/super-admin/plans'
      fullPath: '/super-admin/plans'
      preLoaderRoute: typeof AuthenticatedSuperAdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin/audit': {
      id: '/_authenticated/super-admin/audit'
      path: '/super-admin/audit'
      fullPath: '/super-admin/audit'
      preLoaderRoute: typeof AuthenticatedSuperAdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/workflows': {
      id: '/_authenticated/settings/workflows'
      path: '/settings/workflows'
      fullPath: '/settings/workflows'
      preLoaderRoute: typeof AuthenticatedSettingsWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/warehouses': {
      id: '/_authenticated/settings/warehouses'
      path: '/settings/warehouses'
      fullPath: '/settings/warehouses'
      preLoaderRoute: typeof AuthenticatedSettingsWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/uom': {
      id: '/_authenticated/settings/uom'
      path: '/settings/uom'
      fullPath: '/settings/uom'
      preLoaderRoute: typeof AuthenticatedSettingsUomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/templates': {
      id: '/_authenticated/settings/templates'
      path: '/settings/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof AuthenticatedSettingsTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/taxes': {
      id: '/_authenticated/settings/taxes'
      path: '/settings/taxes'
      fullPath: '/settings/taxes'
      preLoaderRoute: typeof AuthenticatedSettingsTaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/payment-terms': {
      id: '/_authenticated/settings/payment-terms'
      path: '/settings/payment-terms'
      fullPath: '/settings/payment-terms'
      preLoaderRoute: typeof AuthenticatedSettingsPaymentTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/numbering': {
      id: '/_authenticated/settings/numbering'
      path: '/settings/numbering'
      fullPath: '/settings/numbering'
      preLoaderRoute: typeof AuthenticatedSettingsNumberingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/currencies': {
      id: '/_authenticated/settings/currencies'
      path: '/settings/currencies'
      fullPath: '/settings/currencies'
      preLoaderRoute: typeof AuthenticatedSettingsCurrenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/company': {
      id: '/_authenticated/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales/shipments': {
      id: '/_authenticated/sales/shipments'
      path: '/sales/shipments'
      fullPath: '/sales/shipments'
      preLoaderRoute: typeof AuthenticatedSalesShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales/quotes': {
      id: '/_authenticated/sales/quotes'
      path: '/sales/quotes'
      fullPath: '/sales/quotes'
      preLoaderRoute: typeof AuthenticatedSalesQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales/payments': {
      id: '/_authenticated/sales/payments'
      path: '/sales/payments'
      fullPath: '/sales/payments'
      preLoaderRoute: typeof AuthenticatedSalesPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales/packages': {
      id: '/_authenticated/sales/packages'
      path: '/sales/packages'
      fullPath: '/sales/packages'
      preLoaderRoute: typeof AuthenticatedSalesPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales/orders': {
      id: '/_authenticated/sales/orders'
      path: '/sales/orders'
      fullPath: '/sales/orders'
      preLoaderRoute: typeof AuthenticatedSalesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales/invoices': {
      id: '/_authenticated/sales/invoices'
      path: '/sales/invoices'
      fullPath: '/sales/invoices'
      preLoaderRoute: typeof AuthenticatedSalesInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales/credit-notes': {
      id: '/_authenticated/sales/credit-notes'
      path: '/sales/credit-notes'
      fullPath: '/sales/credit-notes'
      preLoaderRoute: typeof AuthenticatedSalesCreditNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/sales': {
      id: '/_authenticated/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AuthenticatedReportsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/purchases': {
      id: '/_authenticated/reports/purchases'
      path: '/reports/purchases'
      fullPath: '/reports/purchases'
      preLoaderRoute: typeof AuthenticatedReportsPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/manufacturing': {
      id: '/_authenticated/reports/manufacturing'
      path: '/reports/manufacturing'
      fullPath: '/reports/manufacturing'
      preLoaderRoute: typeof AuthenticatedReportsManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/inventory': {
      id: '/_authenticated/reports/inventory'
      path: '/reports/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof AuthenticatedReportsInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/financial': {
      id: '/_authenticated/reports/financial'
      path: '/reports/financial'
      fullPath: '/reports/financial'
      preLoaderRoute: typeof AuthenticatedReportsFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/purchasing/suppliers': {
      id: '/_authenticated/purchasing/suppliers'
      path: '/purchasing/suppliers'
      fullPath: '/purchasing/suppliers'
      preLoaderRoute: typeof AuthenticatedPurchasingSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/purchasing/requisitions': {
      id: '/_authenticated/purchasing/requisitions'
      path: '/purchasing/requisitions'
      fullPath: '/purchasing/requisitions'
      preLoaderRoute: typeof AuthenticatedPurchasingRequisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/purchasing/payments': {
      id: '/_authenticated/purchasing/payments'
      path: '/purchasing/payments'
      fullPath: '/purchasing/payments'
      preLoaderRoute: typeof AuthenticatedPurchasingPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/purchasing/orders': {
      id: '/_authenticated/purchasing/orders'
      path: '/purchasing/orders'
      fullPath: '/purchasing/orders'
      preLoaderRoute: typeof AuthenticatedPurchasingOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/purchasing/expenses': {
      id: '/_authenticated/purchasing/expenses'
      path: '/purchasing/expenses'
      fullPath: '/purchasing/expenses'
      preLoaderRoute: typeof AuthenticatedPurchasingExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/purchasing/credits': {
      id: '/_authenticated/purchasing/credits'
      path: '/purchasing/credits'
      fullPath: '/purchasing/credits'
      preLoaderRoute: typeof AuthenticatedPurchasingCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/purchasing/bills': {
      id: '/_authenticated/purchasing/bills'
      path: '/purchasing/bills'
      fullPath: '/purchasing/bills'
      preLoaderRoute: typeof AuthenticatedPurchasingBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manufacturing/runs': {
      id: '/_authenticated/manufacturing/runs'
      path: '/manufacturing/runs'
      fullPath: '/manufacturing/runs'
      preLoaderRoute: typeof AuthenticatedManufacturingRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manufacturing/orders': {
      id: '/_authenticated/manufacturing/orders'
      path: '/manufacturing/orders'
      fullPath: '/manufacturing/orders'
      preLoaderRoute: typeof AuthenticatedManufacturingOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manufacturing/items': {
      id: '/_authenticated/manufacturing/items'
      path: '/manufacturing/items'
      fullPath: '/manufacturing/items'
      preLoaderRoute: typeof AuthenticatedManufacturingItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manufacturing/bom': {
      id: '/_authenticated/manufacturing/bom'
      path: '/manufacturing/bom'
      fullPath: '/manufacturing/bom'
      preLoaderRoute: typeof AuthenticatedManufacturingBomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inventory/warehouses': {
      id: '/_authenticated/inventory/warehouses'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses'
      preLoaderRoute: typeof AuthenticatedInventoryWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inventory/transfers': {
      id: '/_authenticated/inventory/transfers'
      path: '/inventory/transfers'
      fullPath: '/inventory/transfers'
      preLoaderRoute: typeof AuthenticatedInventoryTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inventory/ledger': {
      id: '/_authenticated/inventory/ledger'
      path: '/inventory/ledger'
      fullPath: '/inventory/ledger'
      preLoaderRoute: typeof AuthenticatedInventoryLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inventory/items': {
      id: '/_authenticated/inventory/items'
      path: '/inventory/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof AuthenticatedInventoryItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inventory/adjustments': {
      id: '/_authenticated/inventory/adjustments'
      path: '/inventory/adjustments'
      fullPath: '/inventory/adjustments'
      preLoaderRoute: typeof AuthenticatedInventoryAdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboards/sales': {
      id: '/_authenticated/dashboards/sales'
      path: '/dashboards/sales'
      fullPath: '/dashboards/sales'
      preLoaderRoute: typeof AuthenticatedDashboardsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboards/production': {
      id: '/_authenticated/dashboards/production'
      path: '/dashboards/production'
      fullPath: '/dashboards/production'
      preLoaderRoute: typeof AuthenticatedDashboardsProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboards/procurement': {
      id: '/_authenticated/dashboards/procurement'
      path: '/dashboards/procurement'
      fullPath: '/dashboards/procurement'
      preLoaderRoute: typeof AuthenticatedDashboardsProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboards/logistics': {
      id: '/_authenticated/dashboards/logistics'
      path: '/dashboards/logistics'
      fullPath: '/dashboards/logistics'
      preLoaderRoute: typeof AuthenticatedDashboardsLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crm/customers': {
      id: '/_authenticated/crm/customers'
      path: '/crm/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof AuthenticatedCrmCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounting/reconciliation': {
      id: '/_authenticated/accounting/reconciliation'
      path: '/accounting/reconciliation'
      fullPath: '/accounting/reconciliation'
      preLoaderRoute: typeof AuthenticatedAccountingReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounting/journals': {
      id: '/_authenticated/accounting/journals'
      path: '/accounting/journals'
      fullPath: '/accounting/journals'
      preLoaderRoute: typeof AuthenticatedAccountingJournalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounting/chart': {
      id: '/_authenticated/accounting/chart'
      path: '/accounting/chart'
      fullPath: '/accounting/chart'
      preLoaderRoute: typeof AuthenticatedAccountingChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounting/banking': {
      id: '/_authenticated/accounting/banking'
      path: '/accounting/banking'
      fullPath: '/accounting/banking'
      preLoaderRoute: typeof AuthenticatedAccountingBankingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountingBankingRoute: AuthenticatedAccountingBankingRoute,
  AuthenticatedAccountingChartRoute: AuthenticatedAccountingChartRoute,
  AuthenticatedAccountingJournalsRoute: AuthenticatedAccountingJournalsRoute,
  AuthenticatedAccountingReconciliationRoute:
    AuthenticatedAccountingReconciliationRoute,
  AuthenticatedCrmCustomersRoute: AuthenticatedCrmCustomersRoute,
  AuthenticatedDashboardsLogisticsRoute: AuthenticatedDashboardsLogisticsRoute,
  AuthenticatedDashboardsProcurementRoute:
    AuthenticatedDashboardsProcurementRoute,
  AuthenticatedDashboardsProductionRoute:
    AuthenticatedDashboardsProductionRoute,
  AuthenticatedDashboardsSalesRoute: AuthenticatedDashboardsSalesRoute,
  AuthenticatedInventoryAdjustmentsRoute:
    AuthenticatedInventoryAdjustmentsRoute,
  AuthenticatedInventoryItemsRoute: AuthenticatedInventoryItemsRoute,
  AuthenticatedInventoryLedgerRoute: AuthenticatedInventoryLedgerRoute,
  AuthenticatedInventoryTransfersRoute: AuthenticatedInventoryTransfersRoute,
  AuthenticatedInventoryWarehousesRoute: AuthenticatedInventoryWarehousesRoute,
  AuthenticatedManufacturingBomRoute: AuthenticatedManufacturingBomRoute,
  AuthenticatedManufacturingItemsRoute: AuthenticatedManufacturingItemsRoute,
  AuthenticatedManufacturingOrdersRoute: AuthenticatedManufacturingOrdersRoute,
  AuthenticatedManufacturingRunsRoute: AuthenticatedManufacturingRunsRoute,
  AuthenticatedPurchasingBillsRoute: AuthenticatedPurchasingBillsRoute,
  AuthenticatedPurchasingCreditsRoute: AuthenticatedPurchasingCreditsRoute,
  AuthenticatedPurchasingExpensesRoute: AuthenticatedPurchasingExpensesRoute,
  AuthenticatedPurchasingOrdersRoute: AuthenticatedPurchasingOrdersRoute,
  AuthenticatedPurchasingPaymentsRoute: AuthenticatedPurchasingPaymentsRoute,
  AuthenticatedPurchasingRequisitionsRoute:
    AuthenticatedPurchasingRequisitionsRoute,
  AuthenticatedPurchasingSuppliersRoute: AuthenticatedPurchasingSuppliersRoute,
  AuthenticatedReportsFinancialRoute: AuthenticatedReportsFinancialRoute,
  AuthenticatedReportsInventoryRoute: AuthenticatedReportsInventoryRoute,
  AuthenticatedReportsManufacturingRoute:
    AuthenticatedReportsManufacturingRoute,
  AuthenticatedReportsPurchasesRoute: AuthenticatedReportsPurchasesRoute,
  AuthenticatedReportsSalesRoute: AuthenticatedReportsSalesRoute,
  AuthenticatedSalesCreditNotesRoute: AuthenticatedSalesCreditNotesRoute,
  AuthenticatedSalesInvoicesRoute: AuthenticatedSalesInvoicesRoute,
  AuthenticatedSalesOrdersRoute: AuthenticatedSalesOrdersRoute,
  AuthenticatedSalesPackagesRoute: AuthenticatedSalesPackagesRoute,
  AuthenticatedSalesPaymentsRoute: AuthenticatedSalesPaymentsRoute,
  AuthenticatedSalesQuotesRoute: AuthenticatedSalesQuotesRoute,
  AuthenticatedSalesShipmentsRoute: AuthenticatedSalesShipmentsRoute,
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
  AuthenticatedSettingsCompanyRoute: AuthenticatedSettingsCompanyRoute,
  AuthenticatedSettingsCurrenciesRoute: AuthenticatedSettingsCurrenciesRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsNumberingRoute: AuthenticatedSettingsNumberingRoute,
  AuthenticatedSettingsPaymentTermsRoute:
    AuthenticatedSettingsPaymentTermsRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedSettingsTaxesRoute: AuthenticatedSettingsTaxesRoute,
  AuthenticatedSettingsTemplatesRoute: AuthenticatedSettingsTemplatesRoute,
  AuthenticatedSettingsUomRoute: AuthenticatedSettingsUomRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsWarehousesRoute: AuthenticatedSettingsWarehousesRoute,
  AuthenticatedSettingsWorkflowsRoute: AuthenticatedSettingsWorkflowsRoute,
  AuthenticatedSuperAdminAuditRoute: AuthenticatedSuperAdminAuditRoute,
  AuthenticatedSuperAdminPlansRoute: AuthenticatedSuperAdminPlansRoute,
  AuthenticatedSuperAdminSettingsRoute: AuthenticatedSuperAdminSettingsRoute,
  AuthenticatedSuperAdminTenantsRoute: AuthenticatedSuperAdminTenantsRoute,
  AuthenticatedSuperAdminUsersRoute: AuthenticatedSuperAdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
