/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAuditEventsRouteImport } from './routes/_authenticated/audit-events'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminTenantsRouteImport } from './routes/_admin/tenants'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminPlansRouteImport } from './routes/_admin/plans'
import { Route as AdminAuditRouteImport } from './routes/_admin/audit'
import { Route as AuthenticatedSettingsWorkflowsRouteImport } from './routes/_authenticated/settings.workflows'
import { Route as AuthenticatedSettingsWarehousesRouteImport } from './routes/_authenticated/settings.warehouses'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedSettingsUomRouteImport } from './routes/_authenticated/settings.uom'
import { Route as AuthenticatedSettingsTemplatesRouteImport } from './routes/_authenticated/settings.templates'
import { Route as AuthenticatedSettingsTaxesRouteImport } from './routes/_authenticated/settings.taxes'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings.roles'
import { Route as AuthenticatedSettingsPaymentTermsRouteImport } from './routes/_authenticated/settings.payment-terms'
import { Route as AuthenticatedSettingsNumberingRouteImport } from './routes/_authenticated/settings.numbering'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedSettingsCurrenciesRouteImport } from './routes/_authenticated/settings.currencies'
import { Route as AuthenticatedSettingsCompanyRouteImport } from './routes/_authenticated/settings.company'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings.api-keys'
import { Route as AuthenticatedSalesPaymentsRouteImport } from './routes/_authenticated/sales.payments'
import { Route as AuthenticatedReportsSalesRouteImport } from './routes/_authenticated/reports.sales'
import { Route as AuthenticatedReportsPurchasesRouteImport } from './routes/_authenticated/reports.purchases'
import { Route as AuthenticatedReportsManufacturingRouteImport } from './routes/_authenticated/reports.manufacturing'
import { Route as AuthenticatedReportsInventoryRouteImport } from './routes/_authenticated/reports.inventory'
import { Route as AuthenticatedReportsFinancialRouteImport } from './routes/_authenticated/reports.financial'
import { Route as AuthenticatedPurchasingPaymentsRouteImport } from './routes/_authenticated/purchasing.payments'
import { Route as AuthenticatedPurchasingCreditsRouteImport } from './routes/_authenticated/purchasing.credits'
import { Route as AuthenticatedManufacturingRunsRouteImport } from './routes/_authenticated/manufacturing.runs'
import { Route as AuthenticatedManufacturingOrdersRouteImport } from './routes/_authenticated/manufacturing.orders'
import { Route as AuthenticatedInventoryWarehousesRouteImport } from './routes/_authenticated/inventory.warehouses'
import { Route as AuthenticatedInventoryTransfersRouteImport } from './routes/_authenticated/inventory.transfers'
import { Route as AuthenticatedInventoryLedgerRouteImport } from './routes/_authenticated/inventory.ledger'
import { Route as AuthenticatedInventoryItemsRouteImport } from './routes/_authenticated/inventory.items'
import { Route as AuthenticatedInventoryAdjustmentsRouteImport } from './routes/_authenticated/inventory.adjustments'
import { Route as AuthenticatedDashboardsSalesRouteImport } from './routes/_authenticated/dashboards.sales'
import { Route as AuthenticatedDashboardsProductionRouteImport } from './routes/_authenticated/dashboards.production'
import { Route as AuthenticatedDashboardsProcurementRouteImport } from './routes/_authenticated/dashboards.procurement'
import { Route as AuthenticatedDashboardsLogisticsRouteImport } from './routes/_authenticated/dashboards.logistics'
import { Route as AuthenticatedAccountingTrialBalanceRouteImport } from './routes/_authenticated/accounting.trial-balance'
import { Route as AuthenticatedAccountingReconciliationRouteImport } from './routes/_authenticated/accounting.reconciliation'
import { Route as AuthenticatedAccountingProfitLossRouteImport } from './routes/_authenticated/accounting.profit-loss'
import { Route as AuthenticatedAccountingPeriodsRouteImport } from './routes/_authenticated/accounting.periods'
import { Route as AuthenticatedAccountingLedgerRouteImport } from './routes/_authenticated/accounting.ledger'
import { Route as AuthenticatedAccountingJournalsRouteImport } from './routes/_authenticated/accounting.journals'
import { Route as AuthenticatedAccountingChartRouteImport } from './routes/_authenticated/accounting.chart'
import { Route as AuthenticatedAccountingBankingRouteImport } from './routes/_authenticated/accounting.banking'
import { Route as AuthenticatedAccountingBalanceSheetRouteImport } from './routes/_authenticated/accounting.balance-sheet'
import { Route as AuthenticatedSalesShipmentsIndexRouteImport } from './routes/_authenticated/sales.shipments.index'
import { Route as AuthenticatedSalesQuotesIndexRouteImport } from './routes/_authenticated/sales.quotes.index'
import { Route as AuthenticatedSalesPackagesIndexRouteImport } from './routes/_authenticated/sales.packages.index'
import { Route as AuthenticatedSalesOrdersIndexRouteImport } from './routes/_authenticated/sales.orders.index'
import { Route as AuthenticatedSalesInvoicesIndexRouteImport } from './routes/_authenticated/sales.invoices.index'
import { Route as AuthenticatedSalesCreditNotesIndexRouteImport } from './routes/_authenticated/sales.credit-notes.index'
import { Route as AuthenticatedPurchasingSuppliersIndexRouteImport } from './routes/_authenticated/purchasing.suppliers.index'
import { Route as AuthenticatedPurchasingRequisitionsIndexRouteImport } from './routes/_authenticated/purchasing.requisitions.index'
import { Route as AuthenticatedPurchasingOrdersIndexRouteImport } from './routes/_authenticated/purchasing.orders.index'
import { Route as AuthenticatedPurchasingExpensesIndexRouteImport } from './routes/_authenticated/purchasing.expenses.index'
import { Route as AuthenticatedPurchasingBillsIndexRouteImport } from './routes/_authenticated/purchasing.bills.index'
import { Route as AuthenticatedManufacturingItemsIndexRouteImport } from './routes/_authenticated/manufacturing.items.index'
import { Route as AuthenticatedManufacturingBomIndexRouteImport } from './routes/_authenticated/manufacturing.bom.index'
import { Route as AuthenticatedCrmCustomersIndexRouteImport } from './routes/_authenticated/crm.customers.index'
import { Route as AuthenticatedSalesShipmentsIdRouteImport } from './routes/_authenticated/sales.shipments.$id'
import { Route as AuthenticatedSalesQuotesIdRouteImport } from './routes/_authenticated/sales.quotes.$id'
import { Route as AuthenticatedSalesPackagesIdRouteImport } from './routes/_authenticated/sales.packages.$id'
import { Route as AuthenticatedSalesOrdersIdRouteImport } from './routes/_authenticated/sales.orders.$id'
import { Route as AuthenticatedSalesInvoicesIdRouteImport } from './routes/_authenticated/sales.invoices.$id'
import { Route as AuthenticatedSalesCreditNotesIdRouteImport } from './routes/_authenticated/sales.credit-notes.$id'
import { Route as AuthenticatedPurchasingSuppliersIdRouteImport } from './routes/_authenticated/purchasing.suppliers.$id'
import { Route as AuthenticatedPurchasingRequisitionsIdRouteImport } from './routes/_authenticated/purchasing.requisitions.$id'
import { Route as AuthenticatedPurchasingOrdersIdRouteImport } from './routes/_authenticated/purchasing.orders.$id'
import { Route as AuthenticatedPurchasingExpensesIdRouteImport } from './routes/_authenticated/purchasing.expenses.$id'
import { Route as AuthenticatedPurchasingBillsIdRouteImport } from './routes/_authenticated/purchasing.bills.$id'
import { Route as AuthenticatedManufacturingItemsIdRouteImport } from './routes/_authenticated/manufacturing.items.$id'
import { Route as AuthenticatedManufacturingBomIdRouteImport } from './routes/_authenticated/manufacturing.bom.$id'
import { Route as AuthenticatedCrmCustomersIdRouteImport } from './routes/_authenticated/crm.customers.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditEventsRoute =
  AuthenticatedAuditEventsRouteImport.update({
    id: '/audit-events',
    path: '/audit-events',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedSettingsWorkflowsRoute =
  AuthenticatedSettingsWorkflowsRouteImport.update({
    id: '/settings/workflows',
    path: '/settings/workflows',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsWarehousesRoute =
  AuthenticatedSettingsWarehousesRouteImport.update({
    id: '/settings/warehouses',
    path: '/settings/warehouses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUomRoute =
  AuthenticatedSettingsUomRouteImport.update({
    id: '/settings/uom',
    path: '/settings/uom',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsTemplatesRoute =
  AuthenticatedSettingsTemplatesRouteImport.update({
    id: '/settings/templates',
    path: '/settings/templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsTaxesRoute =
  AuthenticatedSettingsTaxesRouteImport.update({
    id: '/settings/taxes',
    path: '/settings/taxes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPaymentTermsRoute =
  AuthenticatedSettingsPaymentTermsRouteImport.update({
    id: '/settings/payment-terms',
    path: '/settings/payment-terms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNumberingRoute =
  AuthenticatedSettingsNumberingRouteImport.update({
    id: '/settings/numbering',
    path: '/settings/numbering',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCurrenciesRoute =
  AuthenticatedSettingsCurrenciesRouteImport.update({
    id: '/settings/currencies',
    path: '/settings/currencies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsCompanyRoute =
  AuthenticatedSettingsCompanyRouteImport.update({
    id: '/settings/company',
    path: '/settings/company',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesPaymentsRoute =
  AuthenticatedSalesPaymentsRouteImport.update({
    id: '/sales/payments',
    path: '/sales/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsSalesRoute =
  AuthenticatedReportsSalesRouteImport.update({
    id: '/reports/sales',
    path: '/reports/sales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsPurchasesRoute =
  AuthenticatedReportsPurchasesRouteImport.update({
    id: '/reports/purchases',
    path: '/reports/purchases',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsManufacturingRoute =
  AuthenticatedReportsManufacturingRouteImport.update({
    id: '/reports/manufacturing',
    path: '/reports/manufacturing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsInventoryRoute =
  AuthenticatedReportsInventoryRouteImport.update({
    id: '/reports/inventory',
    path: '/reports/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsFinancialRoute =
  AuthenticatedReportsFinancialRouteImport.update({
    id: '/reports/financial',
    path: '/reports/financial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingPaymentsRoute =
  AuthenticatedPurchasingPaymentsRouteImport.update({
    id: '/purchasing/payments',
    path: '/purchasing/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingCreditsRoute =
  AuthenticatedPurchasingCreditsRouteImport.update({
    id: '/purchasing/credits',
    path: '/purchasing/credits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManufacturingRunsRoute =
  AuthenticatedManufacturingRunsRouteImport.update({
    id: '/manufacturing/runs',
    path: '/manufacturing/runs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManufacturingOrdersRoute =
  AuthenticatedManufacturingOrdersRouteImport.update({
    id: '/manufacturing/orders',
    path: '/manufacturing/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryWarehousesRoute =
  AuthenticatedInventoryWarehousesRouteImport.update({
    id: '/inventory/warehouses',
    path: '/inventory/warehouses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryTransfersRoute =
  AuthenticatedInventoryTransfersRouteImport.update({
    id: '/inventory/transfers',
    path: '/inventory/transfers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryLedgerRoute =
  AuthenticatedInventoryLedgerRouteImport.update({
    id: '/inventory/ledger',
    path: '/inventory/ledger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryItemsRoute =
  AuthenticatedInventoryItemsRouteImport.update({
    id: '/inventory/items',
    path: '/inventory/items',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryAdjustmentsRoute =
  AuthenticatedInventoryAdjustmentsRouteImport.update({
    id: '/inventory/adjustments',
    path: '/inventory/adjustments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardsSalesRoute =
  AuthenticatedDashboardsSalesRouteImport.update({
    id: '/dashboards/sales',
    path: '/dashboards/sales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardsProductionRoute =
  AuthenticatedDashboardsProductionRouteImport.update({
    id: '/dashboards/production',
    path: '/dashboards/production',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardsProcurementRoute =
  AuthenticatedDashboardsProcurementRouteImport.update({
    id: '/dashboards/procurement',
    path: '/dashboards/procurement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardsLogisticsRoute =
  AuthenticatedDashboardsLogisticsRouteImport.update({
    id: '/dashboards/logistics',
    path: '/dashboards/logistics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountingTrialBalanceRoute =
  AuthenticatedAccountingTrialBalanceRouteImport.update({
    id: '/accounting/trial-balance',
    path: '/accounting/trial-balance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountingReconciliationRoute =
  AuthenticatedAccountingReconciliationRouteImport.update({
    id: '/accounting/reconciliation',
    path: '/accounting/reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountingProfitLossRoute =
  AuthenticatedAccountingProfitLossRouteImport.update({
    id: '/accounting/profit-loss',
    path: '/accounting/profit-loss',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountingPeriodsRoute =
  AuthenticatedAccountingPeriodsRouteImport.update({
    id: '/accounting/periods',
    path: '/accounting/periods',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountingLedgerRoute =
  AuthenticatedAccountingLedgerRouteImport.update({
    id: '/accounting/ledger',
    path: '/accounting/ledger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountingJournalsRoute =
  AuthenticatedAccountingJournalsRouteImport.update({
    id: '/accounting/journals',
    path: '/accounting/journals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountingChartRoute =
  AuthenticatedAccountingChartRouteImport.update({
    id: '/accounting/chart',
    path: '/accounting/chart',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountingBankingRoute =
  AuthenticatedAccountingBankingRouteImport.update({
    id: '/accounting/banking',
    path: '/accounting/banking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountingBalanceSheetRoute =
  AuthenticatedAccountingBalanceSheetRouteImport.update({
    id: '/accounting/balance-sheet',
    path: '/accounting/balance-sheet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesShipmentsIndexRoute =
  AuthenticatedSalesShipmentsIndexRouteImport.update({
    id: '/sales/shipments/',
    path: '/sales/shipments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesQuotesIndexRoute =
  AuthenticatedSalesQuotesIndexRouteImport.update({
    id: '/sales/quotes/',
    path: '/sales/quotes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesPackagesIndexRoute =
  AuthenticatedSalesPackagesIndexRouteImport.update({
    id: '/sales/packages/',
    path: '/sales/packages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOrdersIndexRoute =
  AuthenticatedSalesOrdersIndexRouteImport.update({
    id: '/sales/orders/',
    path: '/sales/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesInvoicesIndexRoute =
  AuthenticatedSalesInvoicesIndexRouteImport.update({
    id: '/sales/invoices/',
    path: '/sales/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesCreditNotesIndexRoute =
  AuthenticatedSalesCreditNotesIndexRouteImport.update({
    id: '/sales/credit-notes/',
    path: '/sales/credit-notes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingSuppliersIndexRoute =
  AuthenticatedPurchasingSuppliersIndexRouteImport.update({
    id: '/purchasing/suppliers/',
    path: '/purchasing/suppliers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingRequisitionsIndexRoute =
  AuthenticatedPurchasingRequisitionsIndexRouteImport.update({
    id: '/purchasing/requisitions/',
    path: '/purchasing/requisitions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingOrdersIndexRoute =
  AuthenticatedPurchasingOrdersIndexRouteImport.update({
    id: '/purchasing/orders/',
    path: '/purchasing/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingExpensesIndexRoute =
  AuthenticatedPurchasingExpensesIndexRouteImport.update({
    id: '/purchasing/expenses/',
    path: '/purchasing/expenses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingBillsIndexRoute =
  AuthenticatedPurchasingBillsIndexRouteImport.update({
    id: '/purchasing/bills/',
    path: '/purchasing/bills/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManufacturingItemsIndexRoute =
  AuthenticatedManufacturingItemsIndexRouteImport.update({
    id: '/manufacturing/items/',
    path: '/manufacturing/items/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManufacturingBomIndexRoute =
  AuthenticatedManufacturingBomIndexRouteImport.update({
    id: '/manufacturing/bom/',
    path: '/manufacturing/bom/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmCustomersIndexRoute =
  AuthenticatedCrmCustomersIndexRouteImport.update({
    id: '/crm/customers/',
    path: '/crm/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesShipmentsIdRoute =
  AuthenticatedSalesShipmentsIdRouteImport.update({
    id: '/sales/shipments/$id',
    path: '/sales/shipments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesQuotesIdRoute =
  AuthenticatedSalesQuotesIdRouteImport.update({
    id: '/sales/quotes/$id',
    path: '/sales/quotes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesPackagesIdRoute =
  AuthenticatedSalesPackagesIdRouteImport.update({
    id: '/sales/packages/$id',
    path: '/sales/packages/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOrdersIdRoute =
  AuthenticatedSalesOrdersIdRouteImport.update({
    id: '/sales/orders/$id',
    path: '/sales/orders/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesInvoicesIdRoute =
  AuthenticatedSalesInvoicesIdRouteImport.update({
    id: '/sales/invoices/$id',
    path: '/sales/invoices/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesCreditNotesIdRoute =
  AuthenticatedSalesCreditNotesIdRouteImport.update({
    id: '/sales/credit-notes/$id',
    path: '/sales/credit-notes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingSuppliersIdRoute =
  AuthenticatedPurchasingSuppliersIdRouteImport.update({
    id: '/purchasing/suppliers/$id',
    path: '/purchasing/suppliers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingRequisitionsIdRoute =
  AuthenticatedPurchasingRequisitionsIdRouteImport.update({
    id: '/purchasing/requisitions/$id',
    path: '/purchasing/requisitions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingOrdersIdRoute =
  AuthenticatedPurchasingOrdersIdRouteImport.update({
    id: '/purchasing/orders/$id',
    path: '/purchasing/orders/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingExpensesIdRoute =
  AuthenticatedPurchasingExpensesIdRouteImport.update({
    id: '/purchasing/expenses/$id',
    path: '/purchasing/expenses/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingBillsIdRoute =
  AuthenticatedPurchasingBillsIdRouteImport.update({
    id: '/purchasing/bills/$id',
    path: '/purchasing/bills/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManufacturingItemsIdRoute =
  AuthenticatedManufacturingItemsIdRouteImport.update({
    id: '/manufacturing/items/$id',
    path: '/manufacturing/items/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManufacturingBomIdRoute =
  AuthenticatedManufacturingBomIdRouteImport.update({
    id: '/manufacturing/bom/$id',
    path: '/manufacturing/bom/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmCustomersIdRoute =
  AuthenticatedCrmCustomersIdRouteImport.update({
    id: '/crm/customers/$id',
    path: '/crm/customers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AdminAuditRoute
  '/plans': typeof AdminPlansRoute
  '/settings': typeof AdminSettingsRoute
  '/tenants': typeof AdminTenantsRoute
  '/users': typeof AdminUsersRoute
  '/audit-events': typeof AuthenticatedAuditEventsRoute
  '/accounting/balance-sheet': typeof AuthenticatedAccountingBalanceSheetRoute
  '/accounting/banking': typeof AuthenticatedAccountingBankingRoute
  '/accounting/chart': typeof AuthenticatedAccountingChartRoute
  '/accounting/journals': typeof AuthenticatedAccountingJournalsRoute
  '/accounting/ledger': typeof AuthenticatedAccountingLedgerRoute
  '/accounting/periods': typeof AuthenticatedAccountingPeriodsRoute
  '/accounting/profit-loss': typeof AuthenticatedAccountingProfitLossRoute
  '/accounting/reconciliation': typeof AuthenticatedAccountingReconciliationRoute
  '/accounting/trial-balance': typeof AuthenticatedAccountingTrialBalanceRoute
  '/dashboards/logistics': typeof AuthenticatedDashboardsLogisticsRoute
  '/dashboards/procurement': typeof AuthenticatedDashboardsProcurementRoute
  '/dashboards/production': typeof AuthenticatedDashboardsProductionRoute
  '/dashboards/sales': typeof AuthenticatedDashboardsSalesRoute
  '/inventory/adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/inventory/items': typeof AuthenticatedInventoryItemsRoute
  '/inventory/ledger': typeof AuthenticatedInventoryLedgerRoute
  '/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/inventory/warehouses': typeof AuthenticatedInventoryWarehousesRoute
  '/manufacturing/orders': typeof AuthenticatedManufacturingOrdersRoute
  '/manufacturing/runs': typeof AuthenticatedManufacturingRunsRoute
  '/purchasing/credits': typeof AuthenticatedPurchasingCreditsRoute
  '/purchasing/payments': typeof AuthenticatedPurchasingPaymentsRoute
  '/reports/financial': typeof AuthenticatedReportsFinancialRoute
  '/reports/inventory': typeof AuthenticatedReportsInventoryRoute
  '/reports/manufacturing': typeof AuthenticatedReportsManufacturingRoute
  '/reports/purchases': typeof AuthenticatedReportsPurchasesRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/sales/payments': typeof AuthenticatedSalesPaymentsRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/numbering': typeof AuthenticatedSettingsNumberingRoute
  '/settings/payment-terms': typeof AuthenticatedSettingsPaymentTermsRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/taxes': typeof AuthenticatedSettingsTaxesRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/settings/uom': typeof AuthenticatedSettingsUomRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/warehouses': typeof AuthenticatedSettingsWarehousesRoute
  '/settings/workflows': typeof AuthenticatedSettingsWorkflowsRoute
  '/crm/customers/$id': typeof AuthenticatedCrmCustomersIdRoute
  '/manufacturing/bom/$id': typeof AuthenticatedManufacturingBomIdRoute
  '/manufacturing/items/$id': typeof AuthenticatedManufacturingItemsIdRoute
  '/purchasing/bills/$id': typeof AuthenticatedPurchasingBillsIdRoute
  '/purchasing/expenses/$id': typeof AuthenticatedPurchasingExpensesIdRoute
  '/purchasing/orders/$id': typeof AuthenticatedPurchasingOrdersIdRoute
  '/purchasing/requisitions/$id': typeof AuthenticatedPurchasingRequisitionsIdRoute
  '/purchasing/suppliers/$id': typeof AuthenticatedPurchasingSuppliersIdRoute
  '/sales/credit-notes/$id': typeof AuthenticatedSalesCreditNotesIdRoute
  '/sales/invoices/$id': typeof AuthenticatedSalesInvoicesIdRoute
  '/sales/orders/$id': typeof AuthenticatedSalesOrdersIdRoute
  '/sales/packages/$id': typeof AuthenticatedSalesPackagesIdRoute
  '/sales/quotes/$id': typeof AuthenticatedSalesQuotesIdRoute
  '/sales/shipments/$id': typeof AuthenticatedSalesShipmentsIdRoute
  '/crm/customers/': typeof AuthenticatedCrmCustomersIndexRoute
  '/manufacturing/bom/': typeof AuthenticatedManufacturingBomIndexRoute
  '/manufacturing/items/': typeof AuthenticatedManufacturingItemsIndexRoute
  '/purchasing/bills/': typeof AuthenticatedPurchasingBillsIndexRoute
  '/purchasing/expenses/': typeof AuthenticatedPurchasingExpensesIndexRoute
  '/purchasing/orders/': typeof AuthenticatedPurchasingOrdersIndexRoute
  '/purchasing/requisitions/': typeof AuthenticatedPurchasingRequisitionsIndexRoute
  '/purchasing/suppliers/': typeof AuthenticatedPurchasingSuppliersIndexRoute
  '/sales/credit-notes/': typeof AuthenticatedSalesCreditNotesIndexRoute
  '/sales/invoices/': typeof AuthenticatedSalesInvoicesIndexRoute
  '/sales/orders/': typeof AuthenticatedSalesOrdersIndexRoute
  '/sales/packages/': typeof AuthenticatedSalesPackagesIndexRoute
  '/sales/quotes/': typeof AuthenticatedSalesQuotesIndexRoute
  '/sales/shipments/': typeof AuthenticatedSalesShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AdminAuditRoute
  '/plans': typeof AdminPlansRoute
  '/settings': typeof AdminSettingsRoute
  '/tenants': typeof AdminTenantsRoute
  '/users': typeof AdminUsersRoute
  '/audit-events': typeof AuthenticatedAuditEventsRoute
  '/accounting/balance-sheet': typeof AuthenticatedAccountingBalanceSheetRoute
  '/accounting/banking': typeof AuthenticatedAccountingBankingRoute
  '/accounting/chart': typeof AuthenticatedAccountingChartRoute
  '/accounting/journals': typeof AuthenticatedAccountingJournalsRoute
  '/accounting/ledger': typeof AuthenticatedAccountingLedgerRoute
  '/accounting/periods': typeof AuthenticatedAccountingPeriodsRoute
  '/accounting/profit-loss': typeof AuthenticatedAccountingProfitLossRoute
  '/accounting/reconciliation': typeof AuthenticatedAccountingReconciliationRoute
  '/accounting/trial-balance': typeof AuthenticatedAccountingTrialBalanceRoute
  '/dashboards/logistics': typeof AuthenticatedDashboardsLogisticsRoute
  '/dashboards/procurement': typeof AuthenticatedDashboardsProcurementRoute
  '/dashboards/production': typeof AuthenticatedDashboardsProductionRoute
  '/dashboards/sales': typeof AuthenticatedDashboardsSalesRoute
  '/inventory/adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/inventory/items': typeof AuthenticatedInventoryItemsRoute
  '/inventory/ledger': typeof AuthenticatedInventoryLedgerRoute
  '/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/inventory/warehouses': typeof AuthenticatedInventoryWarehousesRoute
  '/manufacturing/orders': typeof AuthenticatedManufacturingOrdersRoute
  '/manufacturing/runs': typeof AuthenticatedManufacturingRunsRoute
  '/purchasing/credits': typeof AuthenticatedPurchasingCreditsRoute
  '/purchasing/payments': typeof AuthenticatedPurchasingPaymentsRoute
  '/reports/financial': typeof AuthenticatedReportsFinancialRoute
  '/reports/inventory': typeof AuthenticatedReportsInventoryRoute
  '/reports/manufacturing': typeof AuthenticatedReportsManufacturingRoute
  '/reports/purchases': typeof AuthenticatedReportsPurchasesRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/sales/payments': typeof AuthenticatedSalesPaymentsRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/numbering': typeof AuthenticatedSettingsNumberingRoute
  '/settings/payment-terms': typeof AuthenticatedSettingsPaymentTermsRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/taxes': typeof AuthenticatedSettingsTaxesRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/settings/uom': typeof AuthenticatedSettingsUomRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/warehouses': typeof AuthenticatedSettingsWarehousesRoute
  '/settings/workflows': typeof AuthenticatedSettingsWorkflowsRoute
  '/crm/customers/$id': typeof AuthenticatedCrmCustomersIdRoute
  '/manufacturing/bom/$id': typeof AuthenticatedManufacturingBomIdRoute
  '/manufacturing/items/$id': typeof AuthenticatedManufacturingItemsIdRoute
  '/purchasing/bills/$id': typeof AuthenticatedPurchasingBillsIdRoute
  '/purchasing/expenses/$id': typeof AuthenticatedPurchasingExpensesIdRoute
  '/purchasing/orders/$id': typeof AuthenticatedPurchasingOrdersIdRoute
  '/purchasing/requisitions/$id': typeof AuthenticatedPurchasingRequisitionsIdRoute
  '/purchasing/suppliers/$id': typeof AuthenticatedPurchasingSuppliersIdRoute
  '/sales/credit-notes/$id': typeof AuthenticatedSalesCreditNotesIdRoute
  '/sales/invoices/$id': typeof AuthenticatedSalesInvoicesIdRoute
  '/sales/orders/$id': typeof AuthenticatedSalesOrdersIdRoute
  '/sales/packages/$id': typeof AuthenticatedSalesPackagesIdRoute
  '/sales/quotes/$id': typeof AuthenticatedSalesQuotesIdRoute
  '/sales/shipments/$id': typeof AuthenticatedSalesShipmentsIdRoute
  '/crm/customers': typeof AuthenticatedCrmCustomersIndexRoute
  '/manufacturing/bom': typeof AuthenticatedManufacturingBomIndexRoute
  '/manufacturing/items': typeof AuthenticatedManufacturingItemsIndexRoute
  '/purchasing/bills': typeof AuthenticatedPurchasingBillsIndexRoute
  '/purchasing/expenses': typeof AuthenticatedPurchasingExpensesIndexRoute
  '/purchasing/orders': typeof AuthenticatedPurchasingOrdersIndexRoute
  '/purchasing/requisitions': typeof AuthenticatedPurchasingRequisitionsIndexRoute
  '/purchasing/suppliers': typeof AuthenticatedPurchasingSuppliersIndexRoute
  '/sales/credit-notes': typeof AuthenticatedSalesCreditNotesIndexRoute
  '/sales/invoices': typeof AuthenticatedSalesInvoicesIndexRoute
  '/sales/orders': typeof AuthenticatedSalesOrdersIndexRoute
  '/sales/packages': typeof AuthenticatedSalesPackagesIndexRoute
  '/sales/quotes': typeof AuthenticatedSalesQuotesIndexRoute
  '/sales/shipments': typeof AuthenticatedSalesShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_admin/audit': typeof AdminAuditRoute
  '/_admin/plans': typeof AdminPlansRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/tenants': typeof AdminTenantsRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_authenticated/audit-events': typeof AuthenticatedAuditEventsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/accounting/balance-sheet': typeof AuthenticatedAccountingBalanceSheetRoute
  '/_authenticated/accounting/banking': typeof AuthenticatedAccountingBankingRoute
  '/_authenticated/accounting/chart': typeof AuthenticatedAccountingChartRoute
  '/_authenticated/accounting/journals': typeof AuthenticatedAccountingJournalsRoute
  '/_authenticated/accounting/ledger': typeof AuthenticatedAccountingLedgerRoute
  '/_authenticated/accounting/periods': typeof AuthenticatedAccountingPeriodsRoute
  '/_authenticated/accounting/profit-loss': typeof AuthenticatedAccountingProfitLossRoute
  '/_authenticated/accounting/reconciliation': typeof AuthenticatedAccountingReconciliationRoute
  '/_authenticated/accounting/trial-balance': typeof AuthenticatedAccountingTrialBalanceRoute
  '/_authenticated/dashboards/logistics': typeof AuthenticatedDashboardsLogisticsRoute
  '/_authenticated/dashboards/procurement': typeof AuthenticatedDashboardsProcurementRoute
  '/_authenticated/dashboards/production': typeof AuthenticatedDashboardsProductionRoute
  '/_authenticated/dashboards/sales': typeof AuthenticatedDashboardsSalesRoute
  '/_authenticated/inventory/adjustments': typeof AuthenticatedInventoryAdjustmentsRoute
  '/_authenticated/inventory/items': typeof AuthenticatedInventoryItemsRoute
  '/_authenticated/inventory/ledger': typeof AuthenticatedInventoryLedgerRoute
  '/_authenticated/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/_authenticated/inventory/warehouses': typeof AuthenticatedInventoryWarehousesRoute
  '/_authenticated/manufacturing/orders': typeof AuthenticatedManufacturingOrdersRoute
  '/_authenticated/manufacturing/runs': typeof AuthenticatedManufacturingRunsRoute
  '/_authenticated/purchasing/credits': typeof AuthenticatedPurchasingCreditsRoute
  '/_authenticated/purchasing/payments': typeof AuthenticatedPurchasingPaymentsRoute
  '/_authenticated/reports/financial': typeof AuthenticatedReportsFinancialRoute
  '/_authenticated/reports/inventory': typeof AuthenticatedReportsInventoryRoute
  '/_authenticated/reports/manufacturing': typeof AuthenticatedReportsManufacturingRoute
  '/_authenticated/reports/purchases': typeof AuthenticatedReportsPurchasesRoute
  '/_authenticated/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/_authenticated/sales/payments': typeof AuthenticatedSalesPaymentsRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/_authenticated/settings/currencies': typeof AuthenticatedSettingsCurrenciesRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/numbering': typeof AuthenticatedSettingsNumberingRoute
  '/_authenticated/settings/payment-terms': typeof AuthenticatedSettingsPaymentTermsRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/taxes': typeof AuthenticatedSettingsTaxesRoute
  '/_authenticated/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/_authenticated/settings/uom': typeof AuthenticatedSettingsUomRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/settings/warehouses': typeof AuthenticatedSettingsWarehousesRoute
  '/_authenticated/settings/workflows': typeof AuthenticatedSettingsWorkflowsRoute
  '/_authenticated/crm/customers/$id': typeof AuthenticatedCrmCustomersIdRoute
  '/_authenticated/manufacturing/bom/$id': typeof AuthenticatedManufacturingBomIdRoute
  '/_authenticated/manufacturing/items/$id': typeof AuthenticatedManufacturingItemsIdRoute
  '/_authenticated/purchasing/bills/$id': typeof AuthenticatedPurchasingBillsIdRoute
  '/_authenticated/purchasing/expenses/$id': typeof AuthenticatedPurchasingExpensesIdRoute
  '/_authenticated/purchasing/orders/$id': typeof AuthenticatedPurchasingOrdersIdRoute
  '/_authenticated/purchasing/requisitions/$id': typeof AuthenticatedPurchasingRequisitionsIdRoute
  '/_authenticated/purchasing/suppliers/$id': typeof AuthenticatedPurchasingSuppliersIdRoute
  '/_authenticated/sales/credit-notes/$id': typeof AuthenticatedSalesCreditNotesIdRoute
  '/_authenticated/sales/invoices/$id': typeof AuthenticatedSalesInvoicesIdRoute
  '/_authenticated/sales/orders/$id': typeof AuthenticatedSalesOrdersIdRoute
  '/_authenticated/sales/packages/$id': typeof AuthenticatedSalesPackagesIdRoute
  '/_authenticated/sales/quotes/$id': typeof AuthenticatedSalesQuotesIdRoute
  '/_authenticated/sales/shipments/$id': typeof AuthenticatedSalesShipmentsIdRoute
  '/_authenticated/crm/customers/': typeof AuthenticatedCrmCustomersIndexRoute
  '/_authenticated/manufacturing/bom/': typeof AuthenticatedManufacturingBomIndexRoute
  '/_authenticated/manufacturing/items/': typeof AuthenticatedManufacturingItemsIndexRoute
  '/_authenticated/purchasing/bills/': typeof AuthenticatedPurchasingBillsIndexRoute
  '/_authenticated/purchasing/expenses/': typeof AuthenticatedPurchasingExpensesIndexRoute
  '/_authenticated/purchasing/orders/': typeof AuthenticatedPurchasingOrdersIndexRoute
  '/_authenticated/purchasing/requisitions/': typeof AuthenticatedPurchasingRequisitionsIndexRoute
  '/_authenticated/purchasing/suppliers/': typeof AuthenticatedPurchasingSuppliersIndexRoute
  '/_authenticated/sales/credit-notes/': typeof AuthenticatedSalesCreditNotesIndexRoute
  '/_authenticated/sales/invoices/': typeof AuthenticatedSalesInvoicesIndexRoute
  '/_authenticated/sales/orders/': typeof AuthenticatedSalesOrdersIndexRoute
  '/_authenticated/sales/packages/': typeof AuthenticatedSalesPackagesIndexRoute
  '/_authenticated/sales/quotes/': typeof AuthenticatedSalesQuotesIndexRoute
  '/_authenticated/sales/shipments/': typeof AuthenticatedSalesShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit'
    | '/plans'
    | '/settings'
    | '/tenants'
    | '/users'
    | '/audit-events'
    | '/accounting/balance-sheet'
    | '/accounting/banking'
    | '/accounting/chart'
    | '/accounting/journals'
    | '/accounting/ledger'
    | '/accounting/periods'
    | '/accounting/profit-loss'
    | '/accounting/reconciliation'
    | '/accounting/trial-balance'
    | '/dashboards/logistics'
    | '/dashboards/procurement'
    | '/dashboards/production'
    | '/dashboards/sales'
    | '/inventory/adjustments'
    | '/inventory/items'
    | '/inventory/ledger'
    | '/inventory/transfers'
    | '/inventory/warehouses'
    | '/manufacturing/orders'
    | '/manufacturing/runs'
    | '/purchasing/credits'
    | '/purchasing/payments'
    | '/reports/financial'
    | '/reports/inventory'
    | '/reports/manufacturing'
    | '/reports/purchases'
    | '/reports/sales'
    | '/sales/payments'
    | '/settings/api-keys'
    | '/settings/company'
    | '/settings/currencies'
    | '/settings/notifications'
    | '/settings/numbering'
    | '/settings/payment-terms'
    | '/settings/roles'
    | '/settings/taxes'
    | '/settings/templates'
    | '/settings/uom'
    | '/settings/users'
    | '/settings/warehouses'
    | '/settings/workflows'
    | '/crm/customers/$id'
    | '/manufacturing/bom/$id'
    | '/manufacturing/items/$id'
    | '/purchasing/bills/$id'
    | '/purchasing/expenses/$id'
    | '/purchasing/orders/$id'
    | '/purchasing/requisitions/$id'
    | '/purchasing/suppliers/$id'
    | '/sales/credit-notes/$id'
    | '/sales/invoices/$id'
    | '/sales/orders/$id'
    | '/sales/packages/$id'
    | '/sales/quotes/$id'
    | '/sales/shipments/$id'
    | '/crm/customers/'
    | '/manufacturing/bom/'
    | '/manufacturing/items/'
    | '/purchasing/bills/'
    | '/purchasing/expenses/'
    | '/purchasing/orders/'
    | '/purchasing/requisitions/'
    | '/purchasing/suppliers/'
    | '/sales/credit-notes/'
    | '/sales/invoices/'
    | '/sales/orders/'
    | '/sales/packages/'
    | '/sales/quotes/'
    | '/sales/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audit'
    | '/plans'
    | '/settings'
    | '/tenants'
    | '/users'
    | '/audit-events'
    | '/accounting/balance-sheet'
    | '/accounting/banking'
    | '/accounting/chart'
    | '/accounting/journals'
    | '/accounting/ledger'
    | '/accounting/periods'
    | '/accounting/profit-loss'
    | '/accounting/reconciliation'
    | '/accounting/trial-balance'
    | '/dashboards/logistics'
    | '/dashboards/procurement'
    | '/dashboards/production'
    | '/dashboards/sales'
    | '/inventory/adjustments'
    | '/inventory/items'
    | '/inventory/ledger'
    | '/inventory/transfers'
    | '/inventory/warehouses'
    | '/manufacturing/orders'
    | '/manufacturing/runs'
    | '/purchasing/credits'
    | '/purchasing/payments'
    | '/reports/financial'
    | '/reports/inventory'
    | '/reports/manufacturing'
    | '/reports/purchases'
    | '/reports/sales'
    | '/sales/payments'
    | '/settings/api-keys'
    | '/settings/company'
    | '/settings/currencies'
    | '/settings/notifications'
    | '/settings/numbering'
    | '/settings/payment-terms'
    | '/settings/roles'
    | '/settings/taxes'
    | '/settings/templates'
    | '/settings/uom'
    | '/settings/users'
    | '/settings/warehouses'
    | '/settings/workflows'
    | '/crm/customers/$id'
    | '/manufacturing/bom/$id'
    | '/manufacturing/items/$id'
    | '/purchasing/bills/$id'
    | '/purchasing/expenses/$id'
    | '/purchasing/orders/$id'
    | '/purchasing/requisitions/$id'
    | '/purchasing/suppliers/$id'
    | '/sales/credit-notes/$id'
    | '/sales/invoices/$id'
    | '/sales/orders/$id'
    | '/sales/packages/$id'
    | '/sales/quotes/$id'
    | '/sales/shipments/$id'
    | '/crm/customers'
    | '/manufacturing/bom'
    | '/manufacturing/items'
    | '/purchasing/bills'
    | '/purchasing/expenses'
    | '/purchasing/orders'
    | '/purchasing/requisitions'
    | '/purchasing/suppliers'
    | '/sales/credit-notes'
    | '/sales/invoices'
    | '/sales/orders'
    | '/sales/packages'
    | '/sales/quotes'
    | '/sales/shipments'
  id:
    | '__root__'
    | '/_admin'
    | '/_authenticated'
    | '/auth'
    | '/_admin/audit'
    | '/_admin/plans'
    | '/_admin/settings'
    | '/_admin/tenants'
    | '/_admin/users'
    | '/_authenticated/audit-events'
    | '/_authenticated/'
    | '/_authenticated/accounting/balance-sheet'
    | '/_authenticated/accounting/banking'
    | '/_authenticated/accounting/chart'
    | '/_authenticated/accounting/journals'
    | '/_authenticated/accounting/ledger'
    | '/_authenticated/accounting/periods'
    | '/_authenticated/accounting/profit-loss'
    | '/_authenticated/accounting/reconciliation'
    | '/_authenticated/accounting/trial-balance'
    | '/_authenticated/dashboards/logistics'
    | '/_authenticated/dashboards/procurement'
    | '/_authenticated/dashboards/production'
    | '/_authenticated/dashboards/sales'
    | '/_authenticated/inventory/adjustments'
    | '/_authenticated/inventory/items'
    | '/_authenticated/inventory/ledger'
    | '/_authenticated/inventory/transfers'
    | '/_authenticated/inventory/warehouses'
    | '/_authenticated/manufacturing/orders'
    | '/_authenticated/manufacturing/runs'
    | '/_authenticated/purchasing/credits'
    | '/_authenticated/purchasing/payments'
    | '/_authenticated/reports/financial'
    | '/_authenticated/reports/inventory'
    | '/_authenticated/reports/manufacturing'
    | '/_authenticated/reports/purchases'
    | '/_authenticated/reports/sales'
    | '/_authenticated/sales/payments'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/company'
    | '/_authenticated/settings/currencies'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/numbering'
    | '/_authenticated/settings/payment-terms'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/taxes'
    | '/_authenticated/settings/templates'
    | '/_authenticated/settings/uom'
    | '/_authenticated/settings/users'
    | '/_authenticated/settings/warehouses'
    | '/_authenticated/settings/workflows'
    | '/_authenticated/crm/customers/$id'
    | '/_authenticated/manufacturing/bom/$id'
    | '/_authenticated/manufacturing/items/$id'
    | '/_authenticated/purchasing/bills/$id'
    | '/_authenticated/purchasing/expenses/$id'
    | '/_authenticated/purchasing/orders/$id'
    | '/_authenticated/purchasing/requisitions/$id'
    | '/_authenticated/purchasing/suppliers/$id'
    | '/_authenticated/sales/credit-notes/$id'
    | '/_authenticated/sales/invoices/$id'
    | '/_authenticated/sales/orders/$id'
    | '/_authenticated/sales/packages/$id'
    | '/_authenticated/sales/quotes/$id'
    | '/_authenticated/sales/shipments/$id'
    | '/_authenticated/crm/customers/'
    | '/_authenticated/manufacturing/bom/'
    | '/_authenticated/manufacturing/items/'
    | '/_authenticated/purchasing/bills/'
    | '/_authenticated/purchasing/expenses/'
    | '/_authenticated/purchasing/orders/'
    | '/_authenticated/purchasing/requisitions/'
    | '/_authenticated/purchasing/suppliers/'
    | '/_authenticated/sales/credit-notes/'
    | '/_authenticated/sales/invoices/'
    | '/_authenticated/sales/orders/'
    | '/_authenticated/sales/packages/'
    | '/_authenticated/sales/quotes/'
    | '/_authenticated/sales/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-events': {
      id: '/_authenticated/audit-events'
      path: '/audit-events'
      fullPath: '/audit-events'
      preLoaderRoute: typeof AuthenticatedAuditEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/tenants': {
      id: '/_admin/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/plans': {
      id: '/_admin/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/audit': {
      id: '/_admin/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/settings/workflows': {
      id: '/_authenticated/settings/workflows'
      path: '/settings/workflows'
      fullPath: '/settings/workflows'
      preLoaderRoute: typeof AuthenticatedSettingsWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/warehouses': {
      id: '/_authenticated/settings/warehouses'
      path: '/settings/warehouses'
      fullPath: '/settings/warehouses'
      preLoaderRoute: typeof AuthenticatedSettingsWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/uom': {
      id: '/_authenticated/settings/uom'
      path: '/settings/uom'
      fullPath: '/settings/uom'
      preLoaderRoute: typeof AuthenticatedSettingsUomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/templates': {
      id: '/_authenticated/settings/templates'
      path: '/settings/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof AuthenticatedSettingsTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/taxes': {
      id: '/_authenticated/settings/taxes'
      path: '/settings/taxes'
      fullPath: '/settings/taxes'
      preLoaderRoute: typeof AuthenticatedSettingsTaxesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/payment-terms': {
      id: '/_authenticated/settings/payment-terms'
      path: '/settings/payment-terms'
      fullPath: '/settings/payment-terms'
      preLoaderRoute: typeof AuthenticatedSettingsPaymentTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/numbering': {
      id: '/_authenticated/settings/numbering'
      path: '/settings/numbering'
      fullPath: '/settings/numbering'
      preLoaderRoute: typeof AuthenticatedSettingsNumberingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/currencies': {
      id: '/_authenticated/settings/currencies'
      path: '/settings/currencies'
      fullPath: '/settings/currencies'
      preLoaderRoute: typeof AuthenticatedSettingsCurrenciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/company': {
      id: '/_authenticated/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/payments': {
      id: '/_authenticated/sales/payments'
      path: '/sales/payments'
      fullPath: '/sales/payments'
      preLoaderRoute: typeof AuthenticatedSalesPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/sales': {
      id: '/_authenticated/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AuthenticatedReportsSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/purchases': {
      id: '/_authenticated/reports/purchases'
      path: '/reports/purchases'
      fullPath: '/reports/purchases'
      preLoaderRoute: typeof AuthenticatedReportsPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/manufacturing': {
      id: '/_authenticated/reports/manufacturing'
      path: '/reports/manufacturing'
      fullPath: '/reports/manufacturing'
      preLoaderRoute: typeof AuthenticatedReportsManufacturingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/inventory': {
      id: '/_authenticated/reports/inventory'
      path: '/reports/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof AuthenticatedReportsInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/financial': {
      id: '/_authenticated/reports/financial'
      path: '/reports/financial'
      fullPath: '/reports/financial'
      preLoaderRoute: typeof AuthenticatedReportsFinancialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/payments': {
      id: '/_authenticated/purchasing/payments'
      path: '/purchasing/payments'
      fullPath: '/purchasing/payments'
      preLoaderRoute: typeof AuthenticatedPurchasingPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/credits': {
      id: '/_authenticated/purchasing/credits'
      path: '/purchasing/credits'
      fullPath: '/purchasing/credits'
      preLoaderRoute: typeof AuthenticatedPurchasingCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manufacturing/runs': {
      id: '/_authenticated/manufacturing/runs'
      path: '/manufacturing/runs'
      fullPath: '/manufacturing/runs'
      preLoaderRoute: typeof AuthenticatedManufacturingRunsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manufacturing/orders': {
      id: '/_authenticated/manufacturing/orders'
      path: '/manufacturing/orders'
      fullPath: '/manufacturing/orders'
      preLoaderRoute: typeof AuthenticatedManufacturingOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/warehouses': {
      id: '/_authenticated/inventory/warehouses'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses'
      preLoaderRoute: typeof AuthenticatedInventoryWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/transfers': {
      id: '/_authenticated/inventory/transfers'
      path: '/inventory/transfers'
      fullPath: '/inventory/transfers'
      preLoaderRoute: typeof AuthenticatedInventoryTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/ledger': {
      id: '/_authenticated/inventory/ledger'
      path: '/inventory/ledger'
      fullPath: '/inventory/ledger'
      preLoaderRoute: typeof AuthenticatedInventoryLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/items': {
      id: '/_authenticated/inventory/items'
      path: '/inventory/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof AuthenticatedInventoryItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/adjustments': {
      id: '/_authenticated/inventory/adjustments'
      path: '/inventory/adjustments'
      fullPath: '/inventory/adjustments'
      preLoaderRoute: typeof AuthenticatedInventoryAdjustmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards/sales': {
      id: '/_authenticated/dashboards/sales'
      path: '/dashboards/sales'
      fullPath: '/dashboards/sales'
      preLoaderRoute: typeof AuthenticatedDashboardsSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards/production': {
      id: '/_authenticated/dashboards/production'
      path: '/dashboards/production'
      fullPath: '/dashboards/production'
      preLoaderRoute: typeof AuthenticatedDashboardsProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards/procurement': {
      id: '/_authenticated/dashboards/procurement'
      path: '/dashboards/procurement'
      fullPath: '/dashboards/procurement'
      preLoaderRoute: typeof AuthenticatedDashboardsProcurementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards/logistics': {
      id: '/_authenticated/dashboards/logistics'
      path: '/dashboards/logistics'
      fullPath: '/dashboards/logistics'
      preLoaderRoute: typeof AuthenticatedDashboardsLogisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/trial-balance': {
      id: '/_authenticated/accounting/trial-balance'
      path: '/accounting/trial-balance'
      fullPath: '/accounting/trial-balance'
      preLoaderRoute: typeof AuthenticatedAccountingTrialBalanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/reconciliation': {
      id: '/_authenticated/accounting/reconciliation'
      path: '/accounting/reconciliation'
      fullPath: '/accounting/reconciliation'
      preLoaderRoute: typeof AuthenticatedAccountingReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/profit-loss': {
      id: '/_authenticated/accounting/profit-loss'
      path: '/accounting/profit-loss'
      fullPath: '/accounting/profit-loss'
      preLoaderRoute: typeof AuthenticatedAccountingProfitLossRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/periods': {
      id: '/_authenticated/accounting/periods'
      path: '/accounting/periods'
      fullPath: '/accounting/periods'
      preLoaderRoute: typeof AuthenticatedAccountingPeriodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/ledger': {
      id: '/_authenticated/accounting/ledger'
      path: '/accounting/ledger'
      fullPath: '/accounting/ledger'
      preLoaderRoute: typeof AuthenticatedAccountingLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/journals': {
      id: '/_authenticated/accounting/journals'
      path: '/accounting/journals'
      fullPath: '/accounting/journals'
      preLoaderRoute: typeof AuthenticatedAccountingJournalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/chart': {
      id: '/_authenticated/accounting/chart'
      path: '/accounting/chart'
      fullPath: '/accounting/chart'
      preLoaderRoute: typeof AuthenticatedAccountingChartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/banking': {
      id: '/_authenticated/accounting/banking'
      path: '/accounting/banking'
      fullPath: '/accounting/banking'
      preLoaderRoute: typeof AuthenticatedAccountingBankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/balance-sheet': {
      id: '/_authenticated/accounting/balance-sheet'
      path: '/accounting/balance-sheet'
      fullPath: '/accounting/balance-sheet'
      preLoaderRoute: typeof AuthenticatedAccountingBalanceSheetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/shipments/': {
      id: '/_authenticated/sales/shipments/'
      path: '/sales/shipments'
      fullPath: '/sales/shipments/'
      preLoaderRoute: typeof AuthenticatedSalesShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/quotes/': {
      id: '/_authenticated/sales/quotes/'
      path: '/sales/quotes'
      fullPath: '/sales/quotes/'
      preLoaderRoute: typeof AuthenticatedSalesQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/packages/': {
      id: '/_authenticated/sales/packages/'
      path: '/sales/packages'
      fullPath: '/sales/packages/'
      preLoaderRoute: typeof AuthenticatedSalesPackagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/orders/': {
      id: '/_authenticated/sales/orders/'
      path: '/sales/orders'
      fullPath: '/sales/orders/'
      preLoaderRoute: typeof AuthenticatedSalesOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/invoices/': {
      id: '/_authenticated/sales/invoices/'
      path: '/sales/invoices'
      fullPath: '/sales/invoices/'
      preLoaderRoute: typeof AuthenticatedSalesInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/credit-notes/': {
      id: '/_authenticated/sales/credit-notes/'
      path: '/sales/credit-notes'
      fullPath: '/sales/credit-notes/'
      preLoaderRoute: typeof AuthenticatedSalesCreditNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/suppliers/': {
      id: '/_authenticated/purchasing/suppliers/'
      path: '/purchasing/suppliers'
      fullPath: '/purchasing/suppliers/'
      preLoaderRoute: typeof AuthenticatedPurchasingSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/requisitions/': {
      id: '/_authenticated/purchasing/requisitions/'
      path: '/purchasing/requisitions'
      fullPath: '/purchasing/requisitions/'
      preLoaderRoute: typeof AuthenticatedPurchasingRequisitionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/orders/': {
      id: '/_authenticated/purchasing/orders/'
      path: '/purchasing/orders'
      fullPath: '/purchasing/orders/'
      preLoaderRoute: typeof AuthenticatedPurchasingOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/expenses/': {
      id: '/_authenticated/purchasing/expenses/'
      path: '/purchasing/expenses'
      fullPath: '/purchasing/expenses/'
      preLoaderRoute: typeof AuthenticatedPurchasingExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/bills/': {
      id: '/_authenticated/purchasing/bills/'
      path: '/purchasing/bills'
      fullPath: '/purchasing/bills/'
      preLoaderRoute: typeof AuthenticatedPurchasingBillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manufacturing/items/': {
      id: '/_authenticated/manufacturing/items/'
      path: '/manufacturing/items'
      fullPath: '/manufacturing/items/'
      preLoaderRoute: typeof AuthenticatedManufacturingItemsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manufacturing/bom/': {
      id: '/_authenticated/manufacturing/bom/'
      path: '/manufacturing/bom'
      fullPath: '/manufacturing/bom/'
      preLoaderRoute: typeof AuthenticatedManufacturingBomIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/customers/': {
      id: '/_authenticated/crm/customers/'
      path: '/crm/customers'
      fullPath: '/crm/customers/'
      preLoaderRoute: typeof AuthenticatedCrmCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/shipments/$id': {
      id: '/_authenticated/sales/shipments/$id'
      path: '/sales/shipments/$id'
      fullPath: '/sales/shipments/$id'
      preLoaderRoute: typeof AuthenticatedSalesShipmentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/quotes/$id': {
      id: '/_authenticated/sales/quotes/$id'
      path: '/sales/quotes/$id'
      fullPath: '/sales/quotes/$id'
      preLoaderRoute: typeof AuthenticatedSalesQuotesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/packages/$id': {
      id: '/_authenticated/sales/packages/$id'
      path: '/sales/packages/$id'
      fullPath: '/sales/packages/$id'
      preLoaderRoute: typeof AuthenticatedSalesPackagesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/orders/$id': {
      id: '/_authenticated/sales/orders/$id'
      path: '/sales/orders/$id'
      fullPath: '/sales/orders/$id'
      preLoaderRoute: typeof AuthenticatedSalesOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/invoices/$id': {
      id: '/_authenticated/sales/invoices/$id'
      path: '/sales/invoices/$id'
      fullPath: '/sales/invoices/$id'
      preLoaderRoute: typeof AuthenticatedSalesInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/credit-notes/$id': {
      id: '/_authenticated/sales/credit-notes/$id'
      path: '/sales/credit-notes/$id'
      fullPath: '/sales/credit-notes/$id'
      preLoaderRoute: typeof AuthenticatedSalesCreditNotesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/suppliers/$id': {
      id: '/_authenticated/purchasing/suppliers/$id'
      path: '/purchasing/suppliers/$id'
      fullPath: '/purchasing/suppliers/$id'
      preLoaderRoute: typeof AuthenticatedPurchasingSuppliersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/requisitions/$id': {
      id: '/_authenticated/purchasing/requisitions/$id'
      path: '/purchasing/requisitions/$id'
      fullPath: '/purchasing/requisitions/$id'
      preLoaderRoute: typeof AuthenticatedPurchasingRequisitionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/orders/$id': {
      id: '/_authenticated/purchasing/orders/$id'
      path: '/purchasing/orders/$id'
      fullPath: '/purchasing/orders/$id'
      preLoaderRoute: typeof AuthenticatedPurchasingOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/expenses/$id': {
      id: '/_authenticated/purchasing/expenses/$id'
      path: '/purchasing/expenses/$id'
      fullPath: '/purchasing/expenses/$id'
      preLoaderRoute: typeof AuthenticatedPurchasingExpensesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/bills/$id': {
      id: '/_authenticated/purchasing/bills/$id'
      path: '/purchasing/bills/$id'
      fullPath: '/purchasing/bills/$id'
      preLoaderRoute: typeof AuthenticatedPurchasingBillsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manufacturing/items/$id': {
      id: '/_authenticated/manufacturing/items/$id'
      path: '/manufacturing/items/$id'
      fullPath: '/manufacturing/items/$id'
      preLoaderRoute: typeof AuthenticatedManufacturingItemsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manufacturing/bom/$id': {
      id: '/_authenticated/manufacturing/bom/$id'
      path: '/manufacturing/bom/$id'
      fullPath: '/manufacturing/bom/$id'
      preLoaderRoute: typeof AuthenticatedManufacturingBomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/customers/$id': {
      id: '/_authenticated/crm/customers/$id'
      path: '/crm/customers/$id'
      fullPath: '/crm/customers/$id'
      preLoaderRoute: typeof AuthenticatedCrmCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditEventsRoute: typeof AuthenticatedAuditEventsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountingBalanceSheetRoute: typeof AuthenticatedAccountingBalanceSheetRoute
  AuthenticatedAccountingBankingRoute: typeof AuthenticatedAccountingBankingRoute
  AuthenticatedAccountingChartRoute: typeof AuthenticatedAccountingChartRoute
  AuthenticatedAccountingJournalsRoute: typeof AuthenticatedAccountingJournalsRoute
  AuthenticatedAccountingLedgerRoute: typeof AuthenticatedAccountingLedgerRoute
  AuthenticatedAccountingPeriodsRoute: typeof AuthenticatedAccountingPeriodsRoute
  AuthenticatedAccountingProfitLossRoute: typeof AuthenticatedAccountingProfitLossRoute
  AuthenticatedAccountingReconciliationRoute: typeof AuthenticatedAccountingReconciliationRoute
  AuthenticatedAccountingTrialBalanceRoute: typeof AuthenticatedAccountingTrialBalanceRoute
  AuthenticatedDashboardsLogisticsRoute: typeof AuthenticatedDashboardsLogisticsRoute
  AuthenticatedDashboardsProcurementRoute: typeof AuthenticatedDashboardsProcurementRoute
  AuthenticatedDashboardsProductionRoute: typeof AuthenticatedDashboardsProductionRoute
  AuthenticatedDashboardsSalesRoute: typeof AuthenticatedDashboardsSalesRoute
  AuthenticatedInventoryAdjustmentsRoute: typeof AuthenticatedInventoryAdjustmentsRoute
  AuthenticatedInventoryItemsRoute: typeof AuthenticatedInventoryItemsRoute
  AuthenticatedInventoryLedgerRoute: typeof AuthenticatedInventoryLedgerRoute
  AuthenticatedInventoryTransfersRoute: typeof AuthenticatedInventoryTransfersRoute
  AuthenticatedInventoryWarehousesRoute: typeof AuthenticatedInventoryWarehousesRoute
  AuthenticatedManufacturingOrdersRoute: typeof AuthenticatedManufacturingOrdersRoute
  AuthenticatedManufacturingRunsRoute: typeof AuthenticatedManufacturingRunsRoute
  AuthenticatedPurchasingCreditsRoute: typeof AuthenticatedPurchasingCreditsRoute
  AuthenticatedPurchasingPaymentsRoute: typeof AuthenticatedPurchasingPaymentsRoute
  AuthenticatedReportsFinancialRoute: typeof AuthenticatedReportsFinancialRoute
  AuthenticatedReportsInventoryRoute: typeof AuthenticatedReportsInventoryRoute
  AuthenticatedReportsManufacturingRoute: typeof AuthenticatedReportsManufacturingRoute
  AuthenticatedReportsPurchasesRoute: typeof AuthenticatedReportsPurchasesRoute
  AuthenticatedReportsSalesRoute: typeof AuthenticatedReportsSalesRoute
  AuthenticatedSalesPaymentsRoute: typeof AuthenticatedSalesPaymentsRoute
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsCompanyRoute: typeof AuthenticatedSettingsCompanyRoute
  AuthenticatedSettingsCurrenciesRoute: typeof AuthenticatedSettingsCurrenciesRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsNumberingRoute: typeof AuthenticatedSettingsNumberingRoute
  AuthenticatedSettingsPaymentTermsRoute: typeof AuthenticatedSettingsPaymentTermsRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsTaxesRoute: typeof AuthenticatedSettingsTaxesRoute
  AuthenticatedSettingsTemplatesRoute: typeof AuthenticatedSettingsTemplatesRoute
  AuthenticatedSettingsUomRoute: typeof AuthenticatedSettingsUomRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsWarehousesRoute: typeof AuthenticatedSettingsWarehousesRoute
  AuthenticatedSettingsWorkflowsRoute: typeof AuthenticatedSettingsWorkflowsRoute
  AuthenticatedCrmCustomersIdRoute: typeof AuthenticatedCrmCustomersIdRoute
  AuthenticatedManufacturingBomIdRoute: typeof AuthenticatedManufacturingBomIdRoute
  AuthenticatedManufacturingItemsIdRoute: typeof AuthenticatedManufacturingItemsIdRoute
  AuthenticatedPurchasingBillsIdRoute: typeof AuthenticatedPurchasingBillsIdRoute
  AuthenticatedPurchasingExpensesIdRoute: typeof AuthenticatedPurchasingExpensesIdRoute
  AuthenticatedPurchasingOrdersIdRoute: typeof AuthenticatedPurchasingOrdersIdRoute
  AuthenticatedPurchasingRequisitionsIdRoute: typeof AuthenticatedPurchasingRequisitionsIdRoute
  AuthenticatedPurchasingSuppliersIdRoute: typeof AuthenticatedPurchasingSuppliersIdRoute
  AuthenticatedSalesCreditNotesIdRoute: typeof AuthenticatedSalesCreditNotesIdRoute
  AuthenticatedSalesInvoicesIdRoute: typeof AuthenticatedSalesInvoicesIdRoute
  AuthenticatedSalesOrdersIdRoute: typeof AuthenticatedSalesOrdersIdRoute
  AuthenticatedSalesPackagesIdRoute: typeof AuthenticatedSalesPackagesIdRoute
  AuthenticatedSalesQuotesIdRoute: typeof AuthenticatedSalesQuotesIdRoute
  AuthenticatedSalesShipmentsIdRoute: typeof AuthenticatedSalesShipmentsIdRoute
  AuthenticatedCrmCustomersIndexRoute: typeof AuthenticatedCrmCustomersIndexRoute
  AuthenticatedManufacturingBomIndexRoute: typeof AuthenticatedManufacturingBomIndexRoute
  AuthenticatedManufacturingItemsIndexRoute: typeof AuthenticatedManufacturingItemsIndexRoute
  AuthenticatedPurchasingBillsIndexRoute: typeof AuthenticatedPurchasingBillsIndexRoute
  AuthenticatedPurchasingExpensesIndexRoute: typeof AuthenticatedPurchasingExpensesIndexRoute
  AuthenticatedPurchasingOrdersIndexRoute: typeof AuthenticatedPurchasingOrdersIndexRoute
  AuthenticatedPurchasingRequisitionsIndexRoute: typeof AuthenticatedPurchasingRequisitionsIndexRoute
  AuthenticatedPurchasingSuppliersIndexRoute: typeof AuthenticatedPurchasingSuppliersIndexRoute
  AuthenticatedSalesCreditNotesIndexRoute: typeof AuthenticatedSalesCreditNotesIndexRoute
  AuthenticatedSalesInvoicesIndexRoute: typeof AuthenticatedSalesInvoicesIndexRoute
  AuthenticatedSalesOrdersIndexRoute: typeof AuthenticatedSalesOrdersIndexRoute
  AuthenticatedSalesPackagesIndexRoute: typeof AuthenticatedSalesPackagesIndexRoute
  AuthenticatedSalesQuotesIndexRoute: typeof AuthenticatedSalesQuotesIndexRoute
  AuthenticatedSalesShipmentsIndexRoute: typeof AuthenticatedSalesShipmentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditEventsRoute: AuthenticatedAuditEventsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountingBalanceSheetRoute:
    AuthenticatedAccountingBalanceSheetRoute,
  AuthenticatedAccountingBankingRoute: AuthenticatedAccountingBankingRoute,
  AuthenticatedAccountingChartRoute: AuthenticatedAccountingChartRoute,
  AuthenticatedAccountingJournalsRoute: AuthenticatedAccountingJournalsRoute,
  AuthenticatedAccountingLedgerRoute: AuthenticatedAccountingLedgerRoute,
  AuthenticatedAccountingPeriodsRoute: AuthenticatedAccountingPeriodsRoute,
  AuthenticatedAccountingProfitLossRoute:
    AuthenticatedAccountingProfitLossRoute,
  AuthenticatedAccountingReconciliationRoute:
    AuthenticatedAccountingReconciliationRoute,
  AuthenticatedAccountingTrialBalanceRoute:
    AuthenticatedAccountingTrialBalanceRoute,
  AuthenticatedDashboardsLogisticsRoute: AuthenticatedDashboardsLogisticsRoute,
  AuthenticatedDashboardsProcurementRoute:
    AuthenticatedDashboardsProcurementRoute,
  AuthenticatedDashboardsProductionRoute:
    AuthenticatedDashboardsProductionRoute,
  AuthenticatedDashboardsSalesRoute: AuthenticatedDashboardsSalesRoute,
  AuthenticatedInventoryAdjustmentsRoute:
    AuthenticatedInventoryAdjustmentsRoute,
  AuthenticatedInventoryItemsRoute: AuthenticatedInventoryItemsRoute,
  AuthenticatedInventoryLedgerRoute: AuthenticatedInventoryLedgerRoute,
  AuthenticatedInventoryTransfersRoute: AuthenticatedInventoryTransfersRoute,
  AuthenticatedInventoryWarehousesRoute: AuthenticatedInventoryWarehousesRoute,
  AuthenticatedManufacturingOrdersRoute: AuthenticatedManufacturingOrdersRoute,
  AuthenticatedManufacturingRunsRoute: AuthenticatedManufacturingRunsRoute,
  AuthenticatedPurchasingCreditsRoute: AuthenticatedPurchasingCreditsRoute,
  AuthenticatedPurchasingPaymentsRoute: AuthenticatedPurchasingPaymentsRoute,
  AuthenticatedReportsFinancialRoute: AuthenticatedReportsFinancialRoute,
  AuthenticatedReportsInventoryRoute: AuthenticatedReportsInventoryRoute,
  AuthenticatedReportsManufacturingRoute:
    AuthenticatedReportsManufacturingRoute,
  AuthenticatedReportsPurchasesRoute: AuthenticatedReportsPurchasesRoute,
  AuthenticatedReportsSalesRoute: AuthenticatedReportsSalesRoute,
  AuthenticatedSalesPaymentsRoute: AuthenticatedSalesPaymentsRoute,
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
  AuthenticatedSettingsCompanyRoute: AuthenticatedSettingsCompanyRoute,
  AuthenticatedSettingsCurrenciesRoute: AuthenticatedSettingsCurrenciesRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsNumberingRoute: AuthenticatedSettingsNumberingRoute,
  AuthenticatedSettingsPaymentTermsRoute:
    AuthenticatedSettingsPaymentTermsRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedSettingsTaxesRoute: AuthenticatedSettingsTaxesRoute,
  AuthenticatedSettingsTemplatesRoute: AuthenticatedSettingsTemplatesRoute,
  AuthenticatedSettingsUomRoute: AuthenticatedSettingsUomRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsWarehousesRoute: AuthenticatedSettingsWarehousesRoute,
  AuthenticatedSettingsWorkflowsRoute: AuthenticatedSettingsWorkflowsRoute,
  AuthenticatedCrmCustomersIdRoute: AuthenticatedCrmCustomersIdRoute,
  AuthenticatedManufacturingBomIdRoute: AuthenticatedManufacturingBomIdRoute,
  AuthenticatedManufacturingItemsIdRoute:
    AuthenticatedManufacturingItemsIdRoute,
  AuthenticatedPurchasingBillsIdRoute: AuthenticatedPurchasingBillsIdRoute,
  AuthenticatedPurchasingExpensesIdRoute:
    AuthenticatedPurchasingExpensesIdRoute,
  AuthenticatedPurchasingOrdersIdRoute: AuthenticatedPurchasingOrdersIdRoute,
  AuthenticatedPurchasingRequisitionsIdRoute:
    AuthenticatedPurchasingRequisitionsIdRoute,
  AuthenticatedPurchasingSuppliersIdRoute:
    AuthenticatedPurchasingSuppliersIdRoute,
  AuthenticatedSalesCreditNotesIdRoute: AuthenticatedSalesCreditNotesIdRoute,
  AuthenticatedSalesInvoicesIdRoute: AuthenticatedSalesInvoicesIdRoute,
  AuthenticatedSalesOrdersIdRoute: AuthenticatedSalesOrdersIdRoute,
  AuthenticatedSalesPackagesIdRoute: AuthenticatedSalesPackagesIdRoute,
  AuthenticatedSalesQuotesIdRoute: AuthenticatedSalesQuotesIdRoute,
  AuthenticatedSalesShipmentsIdRoute: AuthenticatedSalesShipmentsIdRoute,
  AuthenticatedCrmCustomersIndexRoute: AuthenticatedCrmCustomersIndexRoute,
  AuthenticatedManufacturingBomIndexRoute:
    AuthenticatedManufacturingBomIndexRoute,
  AuthenticatedManufacturingItemsIndexRoute:
    AuthenticatedManufacturingItemsIndexRoute,
  AuthenticatedPurchasingBillsIndexRoute:
    AuthenticatedPurchasingBillsIndexRoute,
  AuthenticatedPurchasingExpensesIndexRoute:
    AuthenticatedPurchasingExpensesIndexRoute,
  AuthenticatedPurchasingOrdersIndexRoute:
    AuthenticatedPurchasingOrdersIndexRoute,
  AuthenticatedPurchasingRequisitionsIndexRoute:
    AuthenticatedPurchasingRequisitionsIndexRoute,
  AuthenticatedPurchasingSuppliersIndexRoute:
    AuthenticatedPurchasingSuppliersIndexRoute,
  AuthenticatedSalesCreditNotesIndexRoute:
    AuthenticatedSalesCreditNotesIndexRoute,
  AuthenticatedSalesInvoicesIndexRoute: AuthenticatedSalesInvoicesIndexRoute,
  AuthenticatedSalesOrdersIndexRoute: AuthenticatedSalesOrdersIndexRoute,
  AuthenticatedSalesPackagesIndexRoute: AuthenticatedSalesPackagesIndexRoute,
  AuthenticatedSalesQuotesIndexRoute: AuthenticatedSalesQuotesIndexRoute,
  AuthenticatedSalesShipmentsIndexRoute: AuthenticatedSalesShipmentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
