-- Phase 7: database-driven procurement/AP/expense reporting.

CREATE OR REPLACE FUNCTION public.get_procurement_report(
  _report text DEFAULT 'summary', _date_from date DEFAULT NULL, _date_to date DEFAULT NULL,
  _supplier_id uuid DEFAULT NULL, _currency text DEFAULT NULL, _status text DEFAULT NULL,
  _as_of date DEFAULT CURRENT_DATE
) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE v_tenant uuid := public.current_tenant_id(); v_from date := COALESCE(_date_from, DATE_TRUNC('year', CURRENT_DATE)::date); v_to date := COALESCE(_date_to, CURRENT_DATE); v_as_of date := COALESCE(_as_of, CURRENT_DATE); v_rows jsonb; v_summary jsonb;
BEGIN
  IF NOT public.has_permission('reports.read') THEN RAISE EXCEPTION 'Not authorized: reports.read' USING ERRCODE = '42501'; END IF;
  IF _report = 'summary' THEN
    SELECT jsonb_build_object('gross_purchases',COALESCE(SUM(b.grand_total),0),'net_purchases',COALESCE(SUM(b.subtotal - b.discount_total),0),'tax',COALESCE(SUM(b.tax_total),0),'purchase_orders',COUNT(DISTINCT b.source_po_id),'receipts',(SELECT COUNT(*) FROM public.goods_receipts gr WHERE gr.tenant_id=v_tenant AND gr.receipt_date BETWEEN v_from AND v_to AND gr.deleted_at IS NULL),'supplier_bills',COUNT(*),'outstanding_ap',COALESCE(SUM(b.balance_due),0),'overdue_ap',COALESCE(SUM(CASE WHEN b.due_date < v_as_of AND b.balance_due > 0 THEN b.balance_due ELSE 0 END),0)) INTO v_summary FROM public.bills b WHERE b.tenant_id=v_tenant AND b.date BETWEEN v_from AND v_to AND b.deleted_at IS NULL AND b.posted_at IS NOT NULL AND b.status NOT IN ('Cancelled','Voided') AND (_supplier_id IS NULL OR b.supplier_id=_supplier_id) AND (_currency IS NULL OR b.currency=_currency);
    SELECT COALESCE(jsonb_agg(x ORDER BY x.period), '[]'::jsonb) INTO v_rows FROM (SELECT TO_CHAR(b.date,'YYYY-MM') period, SUM(b.grand_total) total FROM public.bills b WHERE b.tenant_id=v_tenant AND b.date BETWEEN v_from AND v_to AND b.deleted_at IS NULL AND b.posted_at IS NOT NULL GROUP BY 1) x;
  ELSIF _report = 'suppliers' THEN
    SELECT COALESCE(jsonb_agg(x ORDER BY x.gross_purchases DESC),'[]'::jsonb) INTO v_rows FROM (SELECT s.id supplier_id,s.name,COUNT(DISTINCT po.id) po_count,COUNT(DISTINCT b.id) bill_count,COALESCE(SUM(b.grand_total),0) gross_purchases,COALESCE(SUM(b.subtotal-b.discount_total),0) net_purchases,COALESCE(SUM(b.tax_total),0) tax,COALESCE(SUM(pa.paid),0) paid,COALESCE(SUM(b.balance_due),0) outstanding,COALESCE(SUM(CASE WHEN b.due_date<v_as_of AND b.balance_due>0 THEN b.balance_due ELSE 0 END),0) overdue FROM public.suppliers s LEFT JOIN public.purchase_orders po ON po.supplier_id=s.id AND po.tenant_id=v_tenant AND po.deleted_at IS NULL LEFT JOIN public.bills b ON b.supplier_id=s.id AND b.tenant_id=v_tenant AND b.date BETWEEN v_from AND v_to AND b.deleted_at IS NULL AND b.posted_at IS NOT NULL AND b.status NOT IN ('Cancelled','Voided') LEFT JOIN LATERAL (SELECT SUM(a.amount) paid FROM public.supplier_payment_allocations a WHERE a.bill_id=b.id AND a.deleted_at IS NULL) pa ON true WHERE s.tenant_id=v_tenant AND s.deleted_at IS NULL AND (_supplier_id IS NULL OR s.id=_supplier_id) GROUP BY s.id,s.name) x;
  ELSIF _report = 'products' THEN
    SELECT COALESCE(jsonb_agg(x ORDER BY x.gross_spend DESC),'[]'::jsonb) INTO v_rows FROM (SELECT COALESCE(i.name,bl.description,'Unspecified') product,COALESCE(SUM(bl.quantity),0) units_purchased,COALESCE(SUM(bl.line_total),0) gross_spend,COALESCE(SUM(bl.quantity*bl.unit_price*bl.discount_pct/100),0) discount,COALESCE(SUM(bl.line_total-bl.quantity*bl.quantity*0),0) net_spend,COALESCE(SUM(bl.line_total)/NULLIF(SUM(bl.quantity),0),0) average_unit_cost,MAX(bl.unit_price) last_purchase_price,COUNT(DISTINCT b.supplier_id) supplier_count FROM public.bill_lines bl JOIN public.bills b ON b.id=bl.document_id LEFT JOIN public.items i ON i.id=bl.item_id WHERE b.tenant_id=v_tenant AND b.date BETWEEN v_from AND v_to AND b.posted_at IS NOT NULL AND b.deleted_at IS NULL AND bl.deleted_at IS NULL GROUP BY COALESCE(i.name,bl.description,'Unspecified')) x;
  ELSIF _report = 'orders' THEN
    SELECT COALESCE(jsonb_agg(x ORDER BY x.date DESC),'[]'::jsonb) INTO v_rows FROM (SELECT po.id,po.number,po.supplier_id,s.name supplier,po.date,po.expected_date,po.grand_total order_value,po.receiving_status,po.billing_status,po.payment_status,CASE WHEN po.grand_total>0 THEN 100 ELSE 0 END receiving_percent FROM public.purchase_orders po LEFT JOIN public.suppliers s ON s.id=po.supplier_id WHERE po.tenant_id=v_tenant AND po.date BETWEEN v_from AND v_to AND po.deleted_at IS NULL AND (_status IS NULL OR po.status=_status) AND (_supplier_id IS NULL OR po.supplier_id=_supplier_id)) x;
  ELSIF _report = 'commitments' THEN
    SELECT COALESCE(jsonb_agg(x ORDER BY x.remaining_commitment DESC),'[]'::jsonb) INTO v_rows FROM (SELECT po.number,po.supplier_id,s.name supplier,po.grand_total committed,COALESCE((SELECT SUM(grl.accepted_quantity*grl.unit_price) FROM public.goods_receipt_lines grl JOIN public.goods_receipts gr ON gr.id=grl.receipt_id WHERE gr.purchase_order_id=po.id AND gr.status='Posted' AND gr.deleted_at IS NULL AND grl.deleted_at IS NULL),0) received,COALESCE((SELECT SUM(b.grand_total) FROM public.bills b WHERE b.source_po_id=po.id AND b.posted_at IS NOT NULL AND b.deleted_at IS NULL),0) billed,GREATEST(0,po.grand_total-COALESCE((SELECT SUM(b.grand_total) FROM public.bills b WHERE b.source_po_id=po.id AND b.posted_at IS NOT NULL AND b.deleted_at IS NULL),0)) remaining_commitment FROM public.purchase_orders po LEFT JOIN public.suppliers s ON s.id=po.supplier_id WHERE po.tenant_id=v_tenant AND po.status IN ('Approved','Sent','Acknowledged') AND po.deleted_at IS NULL) x;
  ELSIF _report = 'receiving' THEN
    SELECT COALESCE(jsonb_agg(x ORDER BY x.expected_date),'[]'::jsonb) INTO v_rows FROM (SELECT po.number, s.name supplier,po.date,po.expected_date,COALESCE(SUM(pol.quantity),0) ordered,COALESCE(SUM((SELECT SUM(grl.accepted_quantity) FROM public.goods_receipt_lines grl JOIN public.goods_receipts gr ON gr.id=grl.receipt_id WHERE grl.purchase_order_line_id=pol.id AND gr.status='Posted' AND gr.deleted_at IS NULL AND grl.deleted_at IS NULL)),0) received,COALESCE(SUM((SELECT SUM(grl.rejected_quantity) FROM public.goods_receipt_lines grl JOIN public.goods_receipts gr ON gr.id=grl.receipt_id WHERE grl.purchase_order_line_id=pol.id AND gr.status='Posted' AND gr.deleted_at IS NULL AND grl.deleted_at IS NULL)),0) rejected FROM public.purchase_orders po JOIN public.purchase_order_lines pol ON pol.document_id=po.id AND pol.deleted_at IS NULL LEFT JOIN public.suppliers s ON s.id=po.supplier_id WHERE po.tenant_id=v_tenant AND po.deleted_at IS NULL GROUP BY po.id,po.number,s.name,po.date,po.expected_date) x;
  ELSIF _report IN ('matching','price_variance') THEN
    SELECT COALESCE(jsonb_agg(x ORDER BY ABS(x.price_variance) DESC),'[]'::jsonb) INTO v_rows FROM (SELECT b.id bill_id,b.number bill_number,b.source_po_id po_id,b.supplier_id,s.name supplier,COALESCE((public.validate_supplier_bill_against_po(b.id)).match_status,'Not Applicable') match_status,COALESCE((public.validate_supplier_bill_against_po(b.id)).quantity_variance,0) quantity_variance,COALESCE((public.validate_supplier_bill_against_po(b.id)).price_variance,0) price_variance,COALESCE((public.validate_supplier_bill_against_po(b.id)).amount_variance,0) amount_variance FROM public.bills b LEFT JOIN public.suppliers s ON s.id=b.supplier_id WHERE b.tenant_id=v_tenant AND b.date BETWEEN v_from AND v_to AND b.deleted_at IS NULL AND b.source_po_id IS NOT NULL AND (_status IS NULL OR (public.validate_supplier_bill_against_po(b.id)).match_status=_status)) x;
  ELSIF _report = 'payables' THEN
    SELECT COALESCE(jsonb_agg(x ORDER BY x.total_outstanding DESC),'[]'::jsonb) INTO v_rows FROM (SELECT s.id supplier_id,s.name,COALESCE(SUM(CASE WHEN b.due_date IS NULL OR b.due_date>=v_as_of THEN b.balance_due ELSE 0 END),0) current,COALESCE(SUM(CASE WHEN v_as_of-b.due_date BETWEEN 1 AND 30 THEN b.balance_due ELSE 0 END),0) bucket_1_30,COALESCE(SUM(CASE WHEN v_as_of-b.due_date BETWEEN 31 AND 60 THEN b.balance_due ELSE 0 END),0) bucket_31_60,COALESCE(SUM(CASE WHEN v_as_of-b.due_date BETWEEN 61 AND 90 THEN b.balance_due ELSE 0 END),0) bucket_61_90,COALESCE(SUM(CASE WHEN v_as_of-b.due_date>90 THEN b.balance_due ELSE 0 END),0) bucket_over_90,COALESCE(SUM(b.balance_due),0) total_outstanding FROM public.suppliers s LEFT JOIN public.bills b ON b.supplier_id=s.id AND b.tenant_id=v_tenant AND b.posted_at IS NOT NULL AND b.date<=v_as_of AND b.deleted_at IS NULL AND b.status NOT IN ('Cancelled','Voided') WHERE s.tenant_id=v_tenant AND s.deleted_at IS NULL GROUP BY s.id,s.name) x;
  ELSIF _report = 'collections' THEN
    SELECT COALESCE(jsonb_agg(x),'[]'::jsonb) INTO v_rows FROM (SELECT p.id,p.number,p.date,p.supplier_id,s.name supplier,p.amount,COALESCE((SELECT SUM(a.amount) FROM public.supplier_payment_allocations a WHERE a.payment_id=p.id AND a.deleted_at IS NULL),0) allocated,GREATEST(0,p.amount-COALESCE((SELECT SUM(a.amount) FROM public.supplier_payment_allocations a WHERE a.payment_id=p.id AND a.deleted_at IS NULL),0)) unallocated FROM public.payments_made p LEFT JOIN public.suppliers s ON s.id=p.supplier_id WHERE p.tenant_id=v_tenant AND p.date BETWEEN v_from AND v_to AND p.deleted_at IS NULL AND p.voided_at IS NULL) x;
  ELSIF _report = 'supplier_statement' THEN
    SELECT COALESCE(jsonb_agg(x ORDER BY x.date),'[]'::jsonb) INTO v_rows FROM (SELECT b.date,b.number document,b.supplier_invoice_number reference,b.grand_total debit,0::numeric credit FROM public.bills b WHERE b.tenant_id=v_tenant AND b.supplier_id=_supplier_id AND b.posted_at IS NOT NULL AND b.date<=v_as_of AND b.deleted_at IS NULL UNION ALL SELECT p.date,p.number,p.reference,0::numeric,p.amount FROM public.payments_made p WHERE p.tenant_id=v_tenant AND p.supplier_id=_supplier_id AND p.posted_at IS NOT NULL AND p.date<=v_as_of AND p.deleted_at IS NULL) x;
  ELSE RAISE EXCEPTION 'Unknown procurement report: %', _report;
  END IF;
  RETURN jsonb_build_object('report',_report,'from',v_from,'to',v_to,'as_of',v_as_of,'summary',COALESCE(v_summary,'{}'::jsonb),'rows',COALESCE(v_rows,'[]'::jsonb));
END;
$$;

CREATE OR REPLACE FUNCTION public.get_expense_report(
  _report text DEFAULT 'summary', _date_from date DEFAULT NULL, _date_to date DEFAULT NULL,
  _employee_id uuid DEFAULT NULL, _department text DEFAULT NULL, _currency text DEFAULT NULL,
  _status text DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE v_tenant uuid := public.current_tenant_id(); v_from date := COALESCE(_date_from,DATE_TRUNC('year',CURRENT_DATE)::date); v_to date := COALESCE(_date_to,CURRENT_DATE); v_rows jsonb; v_summary jsonb;
BEGIN
  IF NOT public.has_permission('reports.read') THEN RAISE EXCEPTION 'Not authorized: reports.read' USING ERRCODE='42501'; END IF;
  IF _report='summary' THEN SELECT jsonb_build_object('total_expenses',COALESCE(SUM(total),0),'approved',COALESCE(SUM(total) FILTER (WHERE status='Approved'),0),'pending',COALESCE(SUM(total) FILTER (WHERE status IN ('Submitted','Pending Approval')),0),'posted',COALESCE(SUM(total) FILTER (WHERE status='Posted'),0),'reimbursed',COALESCE(SUM(total) FILTER (WHERE reimbursement_status='Reimbursed'),0),'outstanding_reimbursements',COALESCE(SUM(total) FILTER (WHERE reimbursement_status IN ('Pending','Partially Reimbursed')),0)) INTO v_summary FROM public.expenses WHERE tenant_id=v_tenant AND date BETWEEN v_from AND v_to AND deleted_at IS NULL AND (_employee_id IS NULL OR employee_id=_employee_id) AND (_department IS NULL OR department=_department) AND (_currency IS NULL OR currency=_currency);
  ELSIF _report='employees' THEN SELECT COALESCE(jsonb_agg(x ORDER BY x.total DESC),'[]'::jsonb) INTO v_rows FROM (SELECT employee_id,COUNT(*) expense_count,SUM(total) total,SUM(total) FILTER (WHERE reimbursement_status='Reimbursed') reimbursed,SUM(total) FILTER (WHERE reimbursement_status IN ('Pending','Partially Reimbursed')) outstanding FROM public.expenses WHERE tenant_id=v_tenant AND date BETWEEN v_from AND v_to AND deleted_at IS NULL GROUP BY employee_id) x;
  ELSIF _report='categories' THEN SELECT COALESCE(jsonb_agg(x ORDER BY x.total DESC),'[]'::jsonb) INTO v_rows FROM (SELECT category,COUNT(*) count,SUM(total) total,AVG(total) average FROM public.expenses WHERE tenant_id=v_tenant AND date BETWEEN v_from AND v_to AND deleted_at IS NULL GROUP BY category) x;
  ELSIF _report='departments' THEN SELECT COALESCE(jsonb_agg(x ORDER BY x.total DESC),'[]'::jsonb) INTO v_rows FROM (SELECT department,COUNT(*) count,SUM(total) total FROM public.expenses WHERE tenant_id=v_tenant AND date BETWEEN v_from AND v_to AND deleted_at IS NULL GROUP BY department) x;
  ELSIF _report='reimbursements' THEN SELECT COALESCE(jsonb_agg(x ORDER BY x.total DESC),'[]'::jsonb) INTO v_rows FROM (SELECT er.employee_id,COUNT(DISTINCT era.expense_id) expenses,er.total,CASE WHEN er.status='Paid' THEN er.total ELSE 0 END paid,CASE WHEN er.status='Paid' THEN 0 ELSE er.total END outstanding,er.status,er.posted_at payment_date FROM public.employee_reimbursements er LEFT JOIN public.expense_reimbursement_allocations era ON era.reimbursement_id=er.id AND era.deleted_at IS NULL WHERE er.tenant_id=v_tenant AND er.deleted_at IS NULL GROUP BY er.id,er.employee_id,er.total,er.status,er.posted_at) x;
  ELSE RAISE EXCEPTION 'Unknown expense report: %',_report;
  END IF;
  RETURN jsonb_build_object('report',_report,'from',v_from,'to',v_to,'summary',COALESCE(v_summary,'{}'::jsonb),'rows',COALESCE(v_rows,'[]'::jsonb));
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_procurement_report(text,date,date,uuid,text,text,date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_expense_report(text,date,date,uuid,text,text,text) TO authenticated;